apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingora-lb
  namespace: stepflow-demo
  labels:
    app: pingora-lb
    component: load-balancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pingora-lb
  template:
    metadata:
      labels:
        app: pingora-lb
        component: load-balancer
    spec:
      containers:
      - name: pingora
        image: localhost:5000/pingora-lb:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: UPSTREAM_SERVICE
          value: "component-server.stepflow-demo.svc.cluster.local:8080"
        - name: RUST_LOG
          value: "debug"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
