# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.flow_result_failed import FlowResultFailed
    from ..models.flow_result_success import FlowResultSuccess


T = TypeVar("T", bound="DebugShowResponse")


@_attrs_define
class DebugShowResponse:
    """Response from show step

    Attributes:
        step_id (str): Step ID
        completed (bool): Whether the step has been run
        result (FlowResultFailed | FlowResultSuccess | None | Unset):
    """

    step_id: str
    completed: bool
    result: FlowResultFailed | FlowResultSuccess | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.flow_result_failed import FlowResultFailed
        from ..models.flow_result_success import FlowResultSuccess

        step_id = self.step_id

        completed = self.completed

        result: dict[str, Any] | None | Unset
        if isinstance(self.result, Unset):
            result = UNSET
        elif isinstance(self.result, FlowResultSuccess):
            result = self.result.to_dict()
        elif isinstance(self.result, FlowResultFailed):
            result = self.result.to_dict()
        else:
            result = self.result

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "stepId": step_id,
                "completed": completed,
            }
        )
        if result is not UNSET:
            field_dict["result"] = result

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.flow_result_failed import FlowResultFailed
        from ..models.flow_result_success import FlowResultSuccess

        d = dict(src_dict)
        step_id = d.pop("stepId")

        completed = d.pop("completed")

        def _parse_result(
            data: object,
        ) -> FlowResultFailed | FlowResultSuccess | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                componentsschemas_flow_result_type_0 = FlowResultSuccess.from_dict(data)

                return componentsschemas_flow_result_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                componentsschemas_flow_result_type_1 = FlowResultFailed.from_dict(data)

                return componentsschemas_flow_result_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(FlowResultFailed | FlowResultSuccess | None | Unset, data)

        result = _parse_result(d.pop("result", UNSET))

        debug_show_response = cls(
            step_id=step_id,
            completed=completed,
            result=result,
        )

        debug_show_response.additional_properties = d
        return debug_show_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
