# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

# coding: utf-8

"""
Stepflow API

API for Stepflow flows and runs

The version of the OpenAPI document: 0.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Self

from pydantic import (
    BaseModel,
    ConfigDict,
    ValidationError,
    field_validator,
)

from stepflow_api.models.diagnostic_message_one_of import DiagnosticMessageOneOf
from stepflow_api.models.diagnostic_message_one_of1 import DiagnosticMessageOneOf1
from stepflow_api.models.diagnostic_message_one_of2 import DiagnosticMessageOneOf2
from stepflow_api.models.diagnostic_message_one_of3 import DiagnosticMessageOneOf3
from stepflow_api.models.diagnostic_message_one_of4 import DiagnosticMessageOneOf4
from stepflow_api.models.diagnostic_message_one_of5 import DiagnosticMessageOneOf5
from stepflow_api.models.diagnostic_message_one_of6 import DiagnosticMessageOneOf6
from stepflow_api.models.diagnostic_message_one_of7 import DiagnosticMessageOneOf7
from stepflow_api.models.diagnostic_message_one_of8 import DiagnosticMessageOneOf8
from stepflow_api.models.diagnostic_message_one_of9 import DiagnosticMessageOneOf9
from stepflow_api.models.diagnostic_message_one_of10 import DiagnosticMessageOneOf10
from stepflow_api.models.diagnostic_message_one_of11 import DiagnosticMessageOneOf11
from stepflow_api.models.diagnostic_message_one_of12 import DiagnosticMessageOneOf12
from stepflow_api.models.diagnostic_message_one_of13 import DiagnosticMessageOneOf13
from stepflow_api.models.diagnostic_message_one_of14 import DiagnosticMessageOneOf14
from stepflow_api.models.diagnostic_message_one_of15 import DiagnosticMessageOneOf15
from stepflow_api.models.diagnostic_message_one_of16 import DiagnosticMessageOneOf16
from stepflow_api.models.diagnostic_message_one_of17 import DiagnosticMessageOneOf17
from stepflow_api.models.diagnostic_message_one_of18 import DiagnosticMessageOneOf18
from stepflow_api.models.diagnostic_message_one_of19 import DiagnosticMessageOneOf19
from stepflow_api.models.diagnostic_message_one_of20 import DiagnosticMessageOneOf20
from stepflow_api.models.diagnostic_message_one_of21 import DiagnosticMessageOneOf21
from stepflow_api.models.diagnostic_message_one_of22 import DiagnosticMessageOneOf22
from stepflow_api.models.diagnostic_message_one_of23 import DiagnosticMessageOneOf23
from stepflow_api.models.diagnostic_message_one_of24 import DiagnosticMessageOneOf24
from stepflow_api.models.diagnostic_message_one_of25 import DiagnosticMessageOneOf25

DIAGNOSTICMESSAGE_ONE_OF_SCHEMAS = [
    "DiagnosticMessageOneOf",
    "DiagnosticMessageOneOf1",
    "DiagnosticMessageOneOf10",
    "DiagnosticMessageOneOf11",
    "DiagnosticMessageOneOf12",
    "DiagnosticMessageOneOf13",
    "DiagnosticMessageOneOf14",
    "DiagnosticMessageOneOf15",
    "DiagnosticMessageOneOf16",
    "DiagnosticMessageOneOf17",
    "DiagnosticMessageOneOf18",
    "DiagnosticMessageOneOf19",
    "DiagnosticMessageOneOf2",
    "DiagnosticMessageOneOf20",
    "DiagnosticMessageOneOf21",
    "DiagnosticMessageOneOf22",
    "DiagnosticMessageOneOf23",
    "DiagnosticMessageOneOf24",
    "DiagnosticMessageOneOf25",
    "DiagnosticMessageOneOf3",
    "DiagnosticMessageOneOf4",
    "DiagnosticMessageOneOf5",
    "DiagnosticMessageOneOf6",
    "DiagnosticMessageOneOf7",
    "DiagnosticMessageOneOf8",
    "DiagnosticMessageOneOf9",
]


class DiagnosticMessage(BaseModel):
    """
    Specific diagnostic message with context
    """

    # data type: DiagnosticMessageOneOf
    oneof_schema_1_validator: DiagnosticMessageOneOf | None = None
    # data type: DiagnosticMessageOneOf1
    oneof_schema_2_validator: DiagnosticMessageOneOf1 | None = None
    # data type: DiagnosticMessageOneOf2
    oneof_schema_3_validator: DiagnosticMessageOneOf2 | None = None
    # data type: DiagnosticMessageOneOf3
    oneof_schema_4_validator: DiagnosticMessageOneOf3 | None = None
    # data type: DiagnosticMessageOneOf4
    oneof_schema_5_validator: DiagnosticMessageOneOf4 | None = None
    # data type: DiagnosticMessageOneOf5
    oneof_schema_6_validator: DiagnosticMessageOneOf5 | None = None
    # data type: DiagnosticMessageOneOf6
    oneof_schema_7_validator: DiagnosticMessageOneOf6 | None = None
    # data type: DiagnosticMessageOneOf7
    oneof_schema_8_validator: DiagnosticMessageOneOf7 | None = None
    # data type: DiagnosticMessageOneOf8
    oneof_schema_9_validator: DiagnosticMessageOneOf8 | None = None
    # data type: DiagnosticMessageOneOf9
    oneof_schema_10_validator: DiagnosticMessageOneOf9 | None = None
    # data type: DiagnosticMessageOneOf10
    oneof_schema_11_validator: DiagnosticMessageOneOf10 | None = None
    # data type: DiagnosticMessageOneOf11
    oneof_schema_12_validator: DiagnosticMessageOneOf11 | None = None
    # data type: DiagnosticMessageOneOf12
    oneof_schema_13_validator: DiagnosticMessageOneOf12 | None = None
    # data type: DiagnosticMessageOneOf13
    oneof_schema_14_validator: DiagnosticMessageOneOf13 | None = None
    # data type: DiagnosticMessageOneOf14
    oneof_schema_15_validator: DiagnosticMessageOneOf14 | None = None
    # data type: DiagnosticMessageOneOf15
    oneof_schema_16_validator: DiagnosticMessageOneOf15 | None = None
    # data type: DiagnosticMessageOneOf16
    oneof_schema_17_validator: DiagnosticMessageOneOf16 | None = None
    # data type: DiagnosticMessageOneOf17
    oneof_schema_18_validator: DiagnosticMessageOneOf17 | None = None
    # data type: DiagnosticMessageOneOf18
    oneof_schema_19_validator: DiagnosticMessageOneOf18 | None = None
    # data type: DiagnosticMessageOneOf19
    oneof_schema_20_validator: DiagnosticMessageOneOf19 | None = None
    # data type: DiagnosticMessageOneOf20
    oneof_schema_21_validator: DiagnosticMessageOneOf20 | None = None
    # data type: DiagnosticMessageOneOf21
    oneof_schema_22_validator: DiagnosticMessageOneOf21 | None = None
    # data type: DiagnosticMessageOneOf22
    oneof_schema_23_validator: DiagnosticMessageOneOf22 | None = None
    # data type: DiagnosticMessageOneOf23
    oneof_schema_24_validator: DiagnosticMessageOneOf23 | None = None
    # data type: DiagnosticMessageOneOf24
    oneof_schema_25_validator: DiagnosticMessageOneOf24 | None = None
    # data type: DiagnosticMessageOneOf25
    oneof_schema_26_validator: DiagnosticMessageOneOf25 | None = None
    actual_instance: DiagnosticMessageOneOf | DiagnosticMessageOneOf1 | DiagnosticMessageOneOf10 | DiagnosticMessageOneOf11 | DiagnosticMessageOneOf12 | DiagnosticMessageOneOf13 | DiagnosticMessageOneOf14 | DiagnosticMessageOneOf15 | DiagnosticMessageOneOf16 | DiagnosticMessageOneOf17 | DiagnosticMessageOneOf18 | DiagnosticMessageOneOf19 | DiagnosticMessageOneOf2 | DiagnosticMessageOneOf20 | DiagnosticMessageOneOf21 | DiagnosticMessageOneOf22 | DiagnosticMessageOneOf23 | DiagnosticMessageOneOf24 | DiagnosticMessageOneOf25 | DiagnosticMessageOneOf3 | DiagnosticMessageOneOf4 | DiagnosticMessageOneOf5 | DiagnosticMessageOneOf6 | DiagnosticMessageOneOf7 | DiagnosticMessageOneOf8 | DiagnosticMessageOneOf9 | None = None
    one_of_schemas: set[str] = {
        "DiagnosticMessageOneOf",
        "DiagnosticMessageOneOf1",
        "DiagnosticMessageOneOf10",
        "DiagnosticMessageOneOf11",
        "DiagnosticMessageOneOf12",
        "DiagnosticMessageOneOf13",
        "DiagnosticMessageOneOf14",
        "DiagnosticMessageOneOf15",
        "DiagnosticMessageOneOf16",
        "DiagnosticMessageOneOf17",
        "DiagnosticMessageOneOf18",
        "DiagnosticMessageOneOf19",
        "DiagnosticMessageOneOf2",
        "DiagnosticMessageOneOf20",
        "DiagnosticMessageOneOf21",
        "DiagnosticMessageOneOf22",
        "DiagnosticMessageOneOf23",
        "DiagnosticMessageOneOf24",
        "DiagnosticMessageOneOf25",
        "DiagnosticMessageOneOf3",
        "DiagnosticMessageOneOf4",
        "DiagnosticMessageOneOf5",
        "DiagnosticMessageOneOf6",
        "DiagnosticMessageOneOf7",
        "DiagnosticMessageOneOf8",
        "DiagnosticMessageOneOf9",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = DiagnosticMessage.model_construct()
        error_messages = []
        match = 0
        # validate data type: DiagnosticMessageOneOf
        if not isinstance(v, DiagnosticMessageOneOf):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf1
        if not isinstance(v, DiagnosticMessageOneOf1):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf1`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf2
        if not isinstance(v, DiagnosticMessageOneOf2):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf2`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf3
        if not isinstance(v, DiagnosticMessageOneOf3):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf3`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf4
        if not isinstance(v, DiagnosticMessageOneOf4):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf4`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf5
        if not isinstance(v, DiagnosticMessageOneOf5):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf5`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf6
        if not isinstance(v, DiagnosticMessageOneOf6):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf6`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf7
        if not isinstance(v, DiagnosticMessageOneOf7):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf7`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf8
        if not isinstance(v, DiagnosticMessageOneOf8):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf8`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf9
        if not isinstance(v, DiagnosticMessageOneOf9):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf9`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf10
        if not isinstance(v, DiagnosticMessageOneOf10):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf10`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf11
        if not isinstance(v, DiagnosticMessageOneOf11):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf11`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf12
        if not isinstance(v, DiagnosticMessageOneOf12):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf12`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf13
        if not isinstance(v, DiagnosticMessageOneOf13):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf13`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf14
        if not isinstance(v, DiagnosticMessageOneOf14):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf14`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf15
        if not isinstance(v, DiagnosticMessageOneOf15):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf15`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf16
        if not isinstance(v, DiagnosticMessageOneOf16):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf16`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf17
        if not isinstance(v, DiagnosticMessageOneOf17):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf17`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf18
        if not isinstance(v, DiagnosticMessageOneOf18):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf18`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf19
        if not isinstance(v, DiagnosticMessageOneOf19):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf19`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf20
        if not isinstance(v, DiagnosticMessageOneOf20):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf20`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf21
        if not isinstance(v, DiagnosticMessageOneOf21):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf21`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf22
        if not isinstance(v, DiagnosticMessageOneOf22):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf22`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf23
        if not isinstance(v, DiagnosticMessageOneOf23):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf23`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf24
        if not isinstance(v, DiagnosticMessageOneOf24):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf24`"
            )
        else:
            match += 1
        # validate data type: DiagnosticMessageOneOf25
        if not isinstance(v, DiagnosticMessageOneOf25):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DiagnosticMessageOneOf25`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in DiagnosticMessage with oneOf schemas: DiagnosticMessageOneOf, DiagnosticMessageOneOf1, DiagnosticMessageOneOf10, DiagnosticMessageOneOf11, DiagnosticMessageOneOf12, DiagnosticMessageOneOf13, DiagnosticMessageOneOf14, DiagnosticMessageOneOf15, DiagnosticMessageOneOf16, DiagnosticMessageOneOf17, DiagnosticMessageOneOf18, DiagnosticMessageOneOf19, DiagnosticMessageOneOf2, DiagnosticMessageOneOf20, DiagnosticMessageOneOf21, DiagnosticMessageOneOf22, DiagnosticMessageOneOf23, DiagnosticMessageOneOf24, DiagnosticMessageOneOf25, DiagnosticMessageOneOf3, DiagnosticMessageOneOf4, DiagnosticMessageOneOf5, DiagnosticMessageOneOf6, DiagnosticMessageOneOf7, DiagnosticMessageOneOf8, DiagnosticMessageOneOf9. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in DiagnosticMessage with oneOf schemas: DiagnosticMessageOneOf, DiagnosticMessageOneOf1, DiagnosticMessageOneOf10, DiagnosticMessageOneOf11, DiagnosticMessageOneOf12, DiagnosticMessageOneOf13, DiagnosticMessageOneOf14, DiagnosticMessageOneOf15, DiagnosticMessageOneOf16, DiagnosticMessageOneOf17, DiagnosticMessageOneOf18, DiagnosticMessageOneOf19, DiagnosticMessageOneOf2, DiagnosticMessageOneOf20, DiagnosticMessageOneOf21, DiagnosticMessageOneOf22, DiagnosticMessageOneOf23, DiagnosticMessageOneOf24, DiagnosticMessageOneOf25, DiagnosticMessageOneOf3, DiagnosticMessageOneOf4, DiagnosticMessageOneOf5, DiagnosticMessageOneOf6, DiagnosticMessageOneOf7, DiagnosticMessageOneOf8, DiagnosticMessageOneOf9. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: str | dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DiagnosticMessageOneOf
        try:
            instance.actual_instance = DiagnosticMessageOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf1
        try:
            instance.actual_instance = DiagnosticMessageOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf2
        try:
            instance.actual_instance = DiagnosticMessageOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf3
        try:
            instance.actual_instance = DiagnosticMessageOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf4
        try:
            instance.actual_instance = DiagnosticMessageOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf5
        try:
            instance.actual_instance = DiagnosticMessageOneOf5.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf6
        try:
            instance.actual_instance = DiagnosticMessageOneOf6.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf7
        try:
            instance.actual_instance = DiagnosticMessageOneOf7.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf8
        try:
            instance.actual_instance = DiagnosticMessageOneOf8.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf9
        try:
            instance.actual_instance = DiagnosticMessageOneOf9.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf10
        try:
            instance.actual_instance = DiagnosticMessageOneOf10.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf11
        try:
            instance.actual_instance = DiagnosticMessageOneOf11.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf12
        try:
            instance.actual_instance = DiagnosticMessageOneOf12.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf13
        try:
            instance.actual_instance = DiagnosticMessageOneOf13.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf14
        try:
            instance.actual_instance = DiagnosticMessageOneOf14.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf15
        try:
            instance.actual_instance = DiagnosticMessageOneOf15.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf16
        try:
            instance.actual_instance = DiagnosticMessageOneOf16.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf17
        try:
            instance.actual_instance = DiagnosticMessageOneOf17.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf18
        try:
            instance.actual_instance = DiagnosticMessageOneOf18.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf19
        try:
            instance.actual_instance = DiagnosticMessageOneOf19.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf20
        try:
            instance.actual_instance = DiagnosticMessageOneOf20.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf21
        try:
            instance.actual_instance = DiagnosticMessageOneOf21.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf22
        try:
            instance.actual_instance = DiagnosticMessageOneOf22.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf23
        try:
            instance.actual_instance = DiagnosticMessageOneOf23.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf24
        try:
            instance.actual_instance = DiagnosticMessageOneOf24.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DiagnosticMessageOneOf25
        try:
            instance.actual_instance = DiagnosticMessageOneOf25.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into DiagnosticMessage with oneOf schemas: DiagnosticMessageOneOf, DiagnosticMessageOneOf1, DiagnosticMessageOneOf10, DiagnosticMessageOneOf11, DiagnosticMessageOneOf12, DiagnosticMessageOneOf13, DiagnosticMessageOneOf14, DiagnosticMessageOneOf15, DiagnosticMessageOneOf16, DiagnosticMessageOneOf17, DiagnosticMessageOneOf18, DiagnosticMessageOneOf19, DiagnosticMessageOneOf2, DiagnosticMessageOneOf20, DiagnosticMessageOneOf21, DiagnosticMessageOneOf22, DiagnosticMessageOneOf23, DiagnosticMessageOneOf24, DiagnosticMessageOneOf25, DiagnosticMessageOneOf3, DiagnosticMessageOneOf4, DiagnosticMessageOneOf5, DiagnosticMessageOneOf6, DiagnosticMessageOneOf7, DiagnosticMessageOneOf8, DiagnosticMessageOneOf9. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into DiagnosticMessage with oneOf schemas: DiagnosticMessageOneOf, DiagnosticMessageOneOf1, DiagnosticMessageOneOf10, DiagnosticMessageOneOf11, DiagnosticMessageOneOf12, DiagnosticMessageOneOf13, DiagnosticMessageOneOf14, DiagnosticMessageOneOf15, DiagnosticMessageOneOf16, DiagnosticMessageOneOf17, DiagnosticMessageOneOf18, DiagnosticMessageOneOf19, DiagnosticMessageOneOf2, DiagnosticMessageOneOf20, DiagnosticMessageOneOf21, DiagnosticMessageOneOf22, DiagnosticMessageOneOf23, DiagnosticMessageOneOf24, DiagnosticMessageOneOf25, DiagnosticMessageOneOf3, DiagnosticMessageOneOf4, DiagnosticMessageOneOf5, DiagnosticMessageOneOf6, DiagnosticMessageOneOf7, DiagnosticMessageOneOf8, DiagnosticMessageOneOf9. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> dict[str, Any] | DiagnosticMessageOneOf | DiagnosticMessageOneOf1 | DiagnosticMessageOneOf10 | DiagnosticMessageOneOf11 | DiagnosticMessageOneOf12 | DiagnosticMessageOneOf13 | DiagnosticMessageOneOf14 | DiagnosticMessageOneOf15 | DiagnosticMessageOneOf16 | DiagnosticMessageOneOf17 | DiagnosticMessageOneOf18 | DiagnosticMessageOneOf19 | DiagnosticMessageOneOf2 | DiagnosticMessageOneOf20 | DiagnosticMessageOneOf21 | DiagnosticMessageOneOf22 | DiagnosticMessageOneOf23 | DiagnosticMessageOneOf24 | DiagnosticMessageOneOf25 | DiagnosticMessageOneOf3 | DiagnosticMessageOneOf4 | DiagnosticMessageOneOf5 | DiagnosticMessageOneOf6 | DiagnosticMessageOneOf7 | DiagnosticMessageOneOf8 | DiagnosticMessageOneOf9 | None:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
