"""Re-export DiagnosticMessage16 from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize, replace this file. Custom files are preserved during regeneration.
"""

from .generated import DiagnosticMessage16

__all__ = ["DiagnosticMessage16"]
