"""Re-export DiagnosticMessage16 from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize this model, replace this file with a custom implementation.
Custom files (not starting with this docstring pattern) are preserved during regeneration.
"""

from .generated import DiagnosticMessage16

__all__ = ["DiagnosticMessage16"]
