# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.diagnostic_message_type_5_type import DiagnosticMessageType5Type

T = TypeVar("T", bound="DiagnosticMessageType5")


@_attrs_define
class DiagnosticMessageType5:
    """
    Attributes:
        step_id (str):
        field (str):
        reason (str):
        type_ (DiagnosticMessageType5Type):
    """

    step_id: str
    field: str
    reason: str
    type_: DiagnosticMessageType5Type
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        step_id = self.step_id

        field = self.field

        reason = self.reason

        type_ = self.type_.value

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "stepId": step_id,
                "field": field,
                "reason": reason,
                "type": type_,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        step_id = d.pop("stepId")

        field = d.pop("field")

        reason = d.pop("reason")

        type_ = DiagnosticMessageType5Type(d.pop("type"))

        diagnostic_message_type_5 = cls(
            step_id=step_id,
            field=field,
            reason=reason,
            type_=type_,
        )

        diagnostic_message_type_5.additional_properties = d
        return diagnostic_message_type_5

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
