# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.diagnostic_message_type_20_type import DiagnosticMessageType20Type
from ..types import UNSET, Unset

T = TypeVar("T", bound="DiagnosticMessageType20")


@_attrs_define
class DiagnosticMessageType20:
    """
    Attributes:
        path (str):
        property_ (str):
        type_ (DiagnosticMessageType20Type):
        step_id (None | str | Unset):
    """

    path: str
    property_: str
    type_: DiagnosticMessageType20Type
    step_id: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        path = self.path

        property_ = self.property_

        type_ = self.type_.value

        step_id: None | str | Unset
        if isinstance(self.step_id, Unset):
            step_id = UNSET
        else:
            step_id = self.step_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "path": path,
                "property": property_,
                "type": type_,
            }
        )
        if step_id is not UNSET:
            field_dict["stepId"] = step_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        path = d.pop("path")

        property_ = d.pop("property")

        type_ = DiagnosticMessageType20Type(d.pop("type"))

        def _parse_step_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        step_id = _parse_step_id(d.pop("stepId", UNSET))

        diagnostic_message_type_20 = cls(
            path=path,
            property_=property_,
            type_=type_,
            step_id=step_id,
        )

        diagnostic_message_type_20.additional_properties = d
        return diagnostic_message_type_20

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
