"""Re-export Diagnostics from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize, replace this file. Custom files are preserved during regeneration.
"""

from .generated import Diagnostics

__all__ = ["Diagnostics"]
