# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

from enum import Enum


class DiagnosticMessageType12Type(str, Enum):
    MISSINGFLOWNAME = "missingFlowName"

    def __str__(self) -> str:
        return str(self.value)
