"""Re-export DiagnosticMessage6 from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize, replace this file. Custom files are preserved during regeneration.
"""

from .generated import DiagnosticMessage6

__all__ = ["DiagnosticMessage6"]
