"""Re-export ErrorAction4 from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize, replace this file. Custom files are preserved during regeneration.
"""

from .generated import ErrorAction4

__all__ = ["ErrorAction4"]
