"""Re-export Expr2 from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize this model, replace this file with a custom implementation.
Custom files (not starting with this docstring pattern) are preserved during regeneration.
"""

from .generated import Expr2

__all__ = ["Expr2"]
