"""Re-export HealthQuery from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize, replace this file. Custom files are preserved during regeneration.
"""

from .generated import HealthQuery

__all__ = ["HealthQuery"]
