# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

from enum import Enum


class OverrideType(str, Enum):
    JSON_PATCH = "json_patch"
    MERGE_PATCH = "merge_patch"

    def __str__(self) -> str:
        return str(self.value)
