"""Re-export RunSummary from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize this model, replace this file with a custom implementation.
Custom files (not starting with this docstring pattern) are preserved during regeneration.
"""

from .generated import RunSummary

__all__ = ["RunSummary"]
