# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..models.execution_status import ExecutionStatus
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.item_statistics import ItemStatistics
    from ..models.workflow_overrides import WorkflowOverrides


T = TypeVar("T", bound="RunDetails")


@_attrs_define
class RunDetails:
    """Detailed flow run information including inputs.

    Note: Item results are not included here. Use `get_item_results()` to
    fetch item results separately. This design reflects that items are stored
    in a separate table and avoids loading all results when just querying
    run metadata.

        Attributes:
            run_id (UUID):
            flow_id (str): A SHA-256 hash of the blob content, represented as a hexadecimal string.
            status (ExecutionStatus): Status of a workflow execution
            debug_mode (bool):
            created_at (datetime.datetime):
            inputs (list[Any]): Input values for each item in this run.
            flow_name (None | str | Unset):
            flow_label (None | str | Unset):
            items (ItemStatistics | Unset): Statistics about items in a run.
            completed_at (datetime.datetime | None | Unset):
            overrides (None | Unset | WorkflowOverrides):
    """

    run_id: UUID
    flow_id: str
    status: ExecutionStatus
    debug_mode: bool
    created_at: datetime.datetime
    inputs: list[Any]
    flow_name: None | str | Unset = UNSET
    flow_label: None | str | Unset = UNSET
    items: ItemStatistics | Unset = UNSET
    completed_at: datetime.datetime | None | Unset = UNSET
    overrides: None | Unset | WorkflowOverrides = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.workflow_overrides import WorkflowOverrides

        run_id = str(self.run_id)

        flow_id = self.flow_id

        status = self.status.value

        debug_mode = self.debug_mode

        created_at = self.created_at.isoformat()

        inputs = self.inputs

        flow_name: None | str | Unset
        if isinstance(self.flow_name, Unset):
            flow_name = UNSET
        else:
            flow_name = self.flow_name

        flow_label: None | str | Unset
        if isinstance(self.flow_label, Unset):
            flow_label = UNSET
        else:
            flow_label = self.flow_label

        items: dict[str, Any] | Unset = UNSET
        if not isinstance(self.items, Unset):
            items = self.items.to_dict()

        completed_at: None | str | Unset
        if isinstance(self.completed_at, Unset):
            completed_at = UNSET
        elif isinstance(self.completed_at, datetime.datetime):
            completed_at = self.completed_at.isoformat()
        else:
            completed_at = self.completed_at

        overrides: dict[str, Any] | None | Unset
        if isinstance(self.overrides, Unset):
            overrides = UNSET
        elif isinstance(self.overrides, WorkflowOverrides):
            overrides = self.overrides.to_dict()
        else:
            overrides = self.overrides

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "runId": run_id,
                "flowId": flow_id,
                "status": status,
                "debugMode": debug_mode,
                "createdAt": created_at,
                "inputs": inputs,
            }
        )
        if flow_name is not UNSET:
            field_dict["flowName"] = flow_name
        if flow_label is not UNSET:
            field_dict["flowLabel"] = flow_label
        if items is not UNSET:
            field_dict["items"] = items
        if completed_at is not UNSET:
            field_dict["completedAt"] = completed_at
        if overrides is not UNSET:
            field_dict["overrides"] = overrides

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.item_statistics import ItemStatistics
        from ..models.workflow_overrides import WorkflowOverrides

        d = dict(src_dict)
        run_id = UUID(d.pop("runId"))

        flow_id = d.pop("flowId")

        status = ExecutionStatus(d.pop("status"))

        debug_mode = d.pop("debugMode")

        created_at = isoparse(d.pop("createdAt"))

        inputs = cast(list[Any], d.pop("inputs"))

        def _parse_flow_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        flow_name = _parse_flow_name(d.pop("flowName", UNSET))

        def _parse_flow_label(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        flow_label = _parse_flow_label(d.pop("flowLabel", UNSET))

        _items = d.pop("items", UNSET)
        items: ItemStatistics | Unset
        if isinstance(_items, Unset):
            items = UNSET
        else:
            items = ItemStatistics.from_dict(_items)

        def _parse_completed_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                completed_at_type_0 = isoparse(data)

                return completed_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        completed_at = _parse_completed_at(d.pop("completedAt", UNSET))

        def _parse_overrides(data: object) -> None | Unset | WorkflowOverrides:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                overrides_type_1 = WorkflowOverrides.from_dict(data)

                return overrides_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | WorkflowOverrides, data)

        overrides = _parse_overrides(d.pop("overrides", UNSET))

        run_details = cls(
            run_id=run_id,
            flow_id=flow_id,
            status=status,
            debug_mode=debug_mode,
            created_at=created_at,
            inputs=inputs,
            flow_name=flow_name,
            flow_label=flow_label,
            items=items,
            completed_at=completed_at,
            overrides=overrides,
        )

        run_details.additional_properties = d
        return run_details

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
