"""Re-export ValueDependencies2 from generated models.

DO NOT EDIT - Generated by scripts/generate_api_client.py
To customize, replace this file. Custom files are preserved during regeneration.
"""

from .generated import ValueDependencies2

__all__ = ["ValueDependencies2"]
