excludes:
  - docs/.*
  - stepflow-ui/.*
  - .*\.ya?ml
  - .*\.snap
  - .*\.toml
  - .*\.md
  - .*\.ts
  - .*\.json
  - .*\.js
  - LICENSE
  - NOTICE
  - \.gitignore
  - requirements.txt
  - .prettierrc
  - .python-version
  - py.typed
  - uv.lock
  - Cargo.lock
  - __pycache__/.*
  - .*\.pyc
  - .*\.pyo
  - .*\.pyd
  - .*\.egg-info/.*
  - \.pytest_cache/.*
  - \.mypy_cache/.*
  - \.venv/.*
  - venv/.*
  - env.*
  - \.dockerignore

licenses:
  - files: any
    ident: Apache-2.0
    authors:
      - name: "DataStax Inc."
    template: |
      Copyright 2025 DataStax Inc.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.

comments:
  - columns: 100
    extension: rs
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extensions: [py, sh]
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 1
  - columns: 80
    extension: any
    files:
      - "[^/]+/Dockerfile[.a-zA-Z_-]*"
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 1