plugins:
  builtin:
    type: builtin
  python:
    type: pull
    command: uv
    args: ["--project", "../../sdks/python/stepflow-py", "run", "python", "loop_server.py"]
    queueName: python

routes:
  "/builtin/{*component}":
    - plugin: builtin
  "/python/{*component}":
    - plugin: python
