name: 'Langflow Integration Checks'
description: 'Run Langflow integration tests and validation using shared script logic'

inputs:
  python-version:
    description: 'Python version to test with'
    required: false
    default: '3.13'
  uv-version:
    description: 'uv version to install'
    required: false
    default: '0.7.5'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}
      working-directory: integrations/langflow

    - name: Setup Rust toolchain (for stepflow binary)
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Configure Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          stepflow-rs

    - name: Build Stepflow binary (needed for integration tests)
      shell: bash
      run: cargo build
      working-directory: stepflow-rs

    - name: Install Langflow dependencies
      shell: bash
      run: uv sync
      working-directory: integrations/langflow

    # Run Langflow integration checks using the shared script
    - name: Run Langflow integration checks
      shell: bash
      run: ./scripts/check-langflow.sh