[package]
name = "stepflow-observability"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
fastrace = { workspace = true }
fastrace-opentelemetry = { workspace = true }
log = { workspace = true }
logforth = { workspace = true }
logforth-append-opentelemetry = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
error-stack = { workspace = true }
clap = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "run_diagnostic_context"
path = "examples/run_diagnostic_context.rs"
