#!/usr/bin/env python3
# Copyright 2025 DataStax Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

"""Type generation script for Stepflow Python SDK.

Generates msgspec Struct types from JSON schemas for:
- Protocol types (component server communication)
- Config types (orchestrator configuration)
- Flow types (workflow definitions: Flow, Step, ErrorAction, etc.)
"""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path


def _generate_types_content(schema_name: str, verbose: bool = True) -> str:
    """Generate types from a schema file and return the processed content."""
    # Get paths
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent
    schema_path = project_root / "schemas" / f"{schema_name}.json"

    # Check that schema exists
    if not schema_path.exists():
        raise FileNotFoundError(f"Schema file not found at {schema_path}")

    if verbose:
        print(f"Generating {schema_name} types from {schema_path}")

    # Generate to temporary file
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py") as temp_file:
        temp_path = Path(temp_file.name)

        # Run datamodel-code-generator
        cmd = [
            "python",
            "-m",
            "datamodel_code_generator",
            "--input",
            str(schema_path),
            "--output",
            str(temp_path),
            "--input-file-type",
            "jsonschema",
            "--output-model-type",
            "msgspec.Struct",
            "--field-constraints",
            "--use-union-operator",
            "--keyword-only",
            "--target-python-version",
            "3.10",
        ]

        # Use --use-title-as-name for both schemas since both now have valid class name titles
        # protocol.json: "JsonRpcVersion", "InitializeParams", "ComponentExecuteResult", etc.
        cmd.append("--use-title-as-name")

        # Generate integer enums as (int, Enum) subclasses (e.g. ErrorCode)
        cmd.append("--use-subclass-enum")

        if verbose:
            print(f"Running: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            raise RuntimeError(f"Error generating {schema_name}: {result.stderr}")

        if verbose:
            print("✓ Generated to temporary file")

        # Process the generated file to add license header and remove timestamp
        if verbose:
            print(f"Processing generated {schema_name} file...")

        with open(temp_path) as f:
            content = f.read()

        # Parse the content
        lines = content.split("\n")

        # Remove the original generator header and timestamp
        filtered_lines = []
        skip_until_imports = True

        for line in lines:
            # Skip generated header and timestamp lines
            if (
                line.startswith("# generated by datamodel-codegen:")
                or line.startswith("#   filename:")
                or line.startswith("#   timestamp:")
            ):
                continue

            # When we hit the first import, stop skipping
            if line.startswith("from __future__"):
                skip_until_imports = False

            if not skip_until_imports:
                filtered_lines.append(line)

        # Create the license header
        header = [
            "# Copyright 2025 DataStax Inc.",
            "#",
            '# Licensed under the Apache License, Version 2.0 (the "License"); you may not',
            "# use this file except in compliance with the License. You may obtain a copy of",
            "# the License at",
            "#",
            "#     http://www.apache.org/licenses/LICENSE-2.0",
            "#",
            "# Unless required by applicable law or agreed to in writing, software",
            '# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT',
            "# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the",
            "# License for the specific language governing permissions and limitations under",
            "# the License.",
            "",
            f"# Auto-generated {schema_name} types from schemas/{schema_name}.json",
            "# To regenerate this file, run:",
            "#   uv run python generate.py",
            "",
        ]

        # Combine license header with the filtered content
        new_content = "\n".join(header + filtered_lines)

        # Add StrEnum compat for Python 3.10: (str, Enum) changes str() behavior
        # compared to StrEnum, so we use a shim that preserves StrEnum semantics.
        # Handle both "(str, Enum)" bases and bare "StrEnum" imports.
        if "class " in new_content and (
            "(str, Enum)" in new_content or "(StrEnum)" in new_content
        ):
            new_content = new_content.replace("(str, Enum)", "(StrEnum)")

            # Build the compat shim for StrEnum
            strenum_compat = (
                "import sys\n\n"
                "if sys.version_info >= (3, 11):\n"
                "    from enum import StrEnum\n"
                "else:\n"
                "    from enum import Enum\n\n"
                "    class StrEnum(str, Enum):\n"
                "        def __str__(self) -> str:\n"
                "            return self.value  # type: ignore[no-any-return]\n"
            )

            # Replace various import patterns that include StrEnum or Enum
            if "from enum import Enum, IntEnum" in new_content:
                new_content = new_content.replace(
                    "from enum import Enum, IntEnum",
                    f"from enum import IntEnum\n\n{strenum_compat}",
                )
            elif "from enum import Enum" in new_content:
                new_content = new_content.replace(
                    "from enum import Enum",
                    strenum_compat,
                )
            elif "from enum import StrEnum" in new_content:
                new_content = new_content.replace(
                    "from enum import StrEnum",
                    strenum_compat,
                )

        # Fix forward references for recursive types
        new_content = new_content.replace("List[ValueExpr]", "List['ValueExpr']")
        new_content = new_content.replace(
            "Dict[str, ValueExpr]", "Dict[str, 'ValueExpr']"
        )

        # Fix msgspec constraint on union types: ge/le/gt/lt on `int | None`
        # is not allowed by msgspec, so strip numeric constraint lines from
        # Meta() annotations on nullable numeric types
        import re

        new_content = re.sub(
            r"^\s+ge=\d+,?\n",
            "",
            new_content,
            flags=re.MULTILINE,
        )

        if verbose:
            print("✓ Added license header and generation documentation")
            print(f"✓ {schema_name.capitalize()} generation complete!")

        return new_content


def generate_types_from_schema(
    schema_name: str,
    output_filename: str,
    check_only: bool = False,
    output_subdir: str = "worker",
) -> int:
    """Generate types from a schema file.

    Args:
        schema_name: Name of the schema file (without .json extension)
        output_filename: Name of the output Python file
        check_only: If True, only check if files are up to date
        output_subdir: Subdirectory under stepflow_py/ to write to (default: "worker")
    """
    # Get paths
    script_dir = Path(__file__).parent
    output_dir = script_dir / "stepflow-py" / "src" / "stepflow_py" / output_subdir
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / output_filename

    try:
        print(f"Generating {schema_name} types...")
        new_content = _generate_types_content(schema_name, verbose=False)

        if check_only:
            # Compare with existing file
            if output_path.exists():
                with open(output_path) as f:
                    existing_content = f.read()

                if existing_content != new_content:
                    print(f"❌ {schema_name} types are out of date!")
                    return 1
                else:
                    print(f"✅ {schema_name} types are up to date")
            else:
                print(f"❌ {schema_name} types file does not exist!")
                return 1
        else:
            # Write the final content
            with open(output_path, "w") as f:
                f.write(new_content)

    except (FileNotFoundError, RuntimeError) as e:
        print(f"Error: {e}")
        return 1

    return 0


def main():
    """Generate typed models from JSON schemas."""
    parser = argparse.ArgumentParser(
        description="Generate Stepflow Python SDK types from JSON schemas"
    )
    parser.add_argument(
        "--check", action="store_true", help="Check if generated files are up to date"
    )

    args = parser.parse_args()

    # Generate protocol types (msgspec-based, for component server communication)
    result = generate_types_from_schema(
        "protocol", "generated_protocol.py", check_only=args.check
    )
    if result != 0:
        return result

    # Generate config types (msgspec-based, for configuration)
    result = generate_types_from_schema(
        "stepflow-config",
        "_generated_config.py",
        check_only=args.check,
        output_subdir="config",
    )
    if result != 0:
        return result

    # Generate flow types (msgspec-based, for workflow definitions)
    result = generate_types_from_schema(
        "flow",
        "generated_flow.py",
        check_only=args.check,
    )
    if result != 0:
        return result

    return 0


if __name__ == "__main__":
    sys.exit(main())
