apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepflow-load-balancer
  namespace: stepflow-demo
  labels:
    app: stepflow-load-balancer
    component: load-balancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stepflow-load-balancer
  template:
    metadata:
      labels:
        app: stepflow-load-balancer
        component: load-balancer
    spec:
      containers:
      - name: load-balancer
        image: ghcr.io/stepflow-ai/stepflow/stepflow-load-balancer:alpine-0.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: UPSTREAM_SERVICE
          value: "component-server.stepflow-demo.svc.cluster.local:8080"
        - name: RUST_LOG
          value: "debug"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
