[package]
name = "stepflow-plugin"
description = "Types and trait for the step execution plugins."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
dynosaur.workspace = true
error-stack.workspace = true
futures.workspace = true
indexmap.workspace = true
matchit.workspace = true
serde.workspace = true
serde_json.workspace = true
stepflow-core.workspace = true
stepflow-observability.workspace = true
stepflow-state.workspace = true
thiserror.workspace = true
trait-variant.workspace = true
log.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_yaml_ng.workspace = true
