# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gnostic/openapi/v3/annotations.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gnostic/openapi/v3/annotations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import openapiv3_pb2 as gnostic_dot_openapi_dot_v3_dot_openapiv3__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$gnostic/openapi/v3/annotations.proto\x12\x12gnostic.openapi.v3\x1a\"gnostic/openapi/v3/openapiv3.proto\x1a google/protobuf/descriptor.proto:M\n\x08\x64ocument\x12\x1c.google.protobuf.FileOptions\x18\xf7\x08 \x01(\x0b\x32\x1c.gnostic.openapi.v3.Document:Q\n\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xf7\x08 \x01(\x0b\x32\x1d.gnostic.openapi.v3.Operation:L\n\x06schema\x12\x1f.google.protobuf.MessageOptions\x18\xf7\x08 \x01(\x0b\x32\x1a.gnostic.openapi.v3.Schema:L\n\x08property\x12\x1d.google.protobuf.FieldOptions\x18\xf7\x08 \x01(\x0b\x32\x1a.gnostic.openapi.v3.SchemaBZ\n\x0eorg.openapi_v3B\x10\x41nnotationsProtoP\x01Z.github.com/google/gnostic/openapiv3;openapi_v3\xa2\x02\x03OASb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gnostic.openapi.v3.annotations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016org.openapi_v3B\020AnnotationsProtoP\001Z.github.com/google/gnostic/openapiv3;openapi_v3\242\002\003OAS'
# @@protoc_insertion_point(module_scope)
