# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.flow_response import FlowResponse
from ...types import Response


def _get_kwargs(
    flow_id: str,
) -> dict[str, Any]:
    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/flows/{flow_id}".format(
            flow_id=quote(str(flow_id), safe=""),
        ),
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | FlowResponse | None:
    if response.status_code == 200:
        response_200 = FlowResponse.from_dict(response.json())

        return response_200

    if response.status_code == 404:
        response_404 = cast(Any, None)
        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | FlowResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    flow_id: str,
    *,
    client: AuthenticatedClient | Client,
) -> Response[Any | FlowResponse]:
    """Get a flow by its ID

    Args:
        flow_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | FlowResponse]
    """

    kwargs = _get_kwargs(
        flow_id=flow_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    flow_id: str,
    *,
    client: AuthenticatedClient | Client,
) -> Any | FlowResponse | None:
    """Get a flow by its ID

    Args:
        flow_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | FlowResponse
    """

    return sync_detailed(
        flow_id=flow_id,
        client=client,
    ).parsed


async def asyncio_detailed(
    flow_id: str,
    *,
    client: AuthenticatedClient | Client,
) -> Response[Any | FlowResponse]:
    """Get a flow by its ID

    Args:
        flow_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | FlowResponse]
    """

    kwargs = _get_kwargs(
        flow_id=flow_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    flow_id: str,
    *,
    client: AuthenticatedClient | Client,
) -> Any | FlowResponse | None:
    """Get a flow by its ID

    Args:
        flow_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | FlowResponse
    """

    return (
        await asyncio_detailed(
            flow_id=flow_id,
            client=client,
        )
    ).parsed
