plugins:
  python:
    type: grpc
    command: uv
    args: ["--project", "../../sdks/python/stepflow-py", "run", "stepflow_worker"]
    queueName: python
  builtin:
    type: builtin
routes:
  "/python/{*component}":
    - plugin: python
  "/{*component}":
    - plugin: builtin
