# Grafana datasources provisioning for Stepflow observability
#
# This file automatically configures datasources when Grafana starts.
# No manual configuration needed in the Grafana UI.

apiVersion: 1

datasources:
  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      exemplarTraceIdDestinations:
        # Link metrics to traces (exemplars)
        - name: trace_id
          datasourceUid: jaeger

  # Loki datasource for logs
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        # Extract trace_id from logs and link to Jaeger
        - datasourceUid: jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
        # Extract run_id from logs
        - matcherRegex: "run_id=(\\w+)"
          name: RunID
          url: ""

  # Jaeger datasource for traces
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    editable: true
    jsonData:
      tracesToLogs:
        # Link traces to logs in Loki
        datasourceUid: 'loki'
        tags: ['run_id', 'step_id']
        mappedTags: [{ key: 'service.name', value: 'service_name' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1m'
        spanEndTimeShift: '1m'
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true
