schema: https://stepflow.org/schemas/v1/flow.json
name: AI Research Assistant
description: Combines LangChain AI processing with MCP filesystem tools to create
  an automated research workflow
input_schema:
  type: object
  properties:
    topic:
      type: string
      description: Research topic to explore
    initial_context:
      type: string
      description: Initial context or background information about the topic
    output_dir:
      type: string
      description: Directory to save research files
      default: /tmp/research
  required:
  - topic
  - initial_context
output_schema:
  type: object
  properties:
    research_questions:
      type: object
      description: Generated research questions
    analysis_summary:
      type: object
      description: Analysis of the initial context
    created_files:
      type: array
      description: List of created research files
    report_location:
      type: string
      description: Location of saved research
steps:
- id: generate_questions
  component: /research/question_generator
  input:
    input:
      topic:
        $input: topic
      context:
        $input: initial_context
    execution_mode: invoke
- id: analyze_context
  component: /research/text_analyzer
  input:
    input:
      text:
        $input: initial_context
      topic:
        $input: topic
      analysis_type: research_summary
    execution_mode: invoke
- id: generate_notes
  component: /research/note_generator
  input:
    input:
      topic:
        $input: topic
      questions:
        $step: generate_questions
        path: questions
      analysis:
        $step: analyze_context
        path: summary
    execution_mode: invoke
- id: create_output_dir
  component: /filesystem/create_directory
  depends_on:
  - generate_questions
  - analyze_context
  - generate_notes
  input:
    path:
      $input: output_dir
- id: save_questions
  component: /filesystem/write_file
  depends_on:
  - create_output_dir
  input:
    path:
      $template: '{{output_dir}}/research_questions.md'
      values:
        output_dir:
          $input: output_dir
    content:
      $step: generate_questions
      path: formatted_output
- id: save_notes
  component: /filesystem/write_file
  depends_on:
  - create_output_dir
  input:
    path:
      $template: '{{output_dir}}/research_notes.md'
      values:
        output_dir:
          $input: output_dir
    content:
      $step: generate_notes
      path: notes
- id: save_analysis
  component: /filesystem/write_file
  depends_on:
  - create_output_dir
  input:
    path:
      $template: '{{output_dir}}/analysis_summary.md'
      values:
        output_dir:
          $input: output_dir
    content:
      $step: analyze_context
      path: formatted_analysis
- id: create_report
  component: /research/report_generator
  input:
    input:
      topic:
        $input: topic
      questions:
        $step: generate_questions
      analysis:
        $step: analyze_context
      notes:
        $step: generate_notes
    execution_mode: invoke
- id: save_report
  component: /filesystem/write_file
  depends_on:
  - create_output_dir
  - create_report
  input:
    path:
      $template: '{{output_dir}}/research_report.json'
      values:
        output_dir:
          $input: output_dir
    content:
      $template: '{{report}}'
      values:
        report:
          $step: create_report
          path: report_json
- id: list_research_files
  component: /filesystem/list_directory
  depends_on:
  - save_questions
  - save_notes
  - save_analysis
  - save_report
  input:
    path:
      $input: output_dir
output:
  research_questions:
    $step: generate_questions
  analysis_summary:
    $step: analyze_context
  created_files:
    $step: list_research_files
  report_location:
    $template: 'Research saved to: {{output_dir}}'
    values:
      output_dir:
        $input: output_dir
