"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ExecutionStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ExecutionStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ExecutionStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EXECUTION_STATUS_UNSPECIFIED: _ExecutionStatus.ValueType  # 0
    EXECUTION_STATUS_RUNNING: _ExecutionStatus.ValueType  # 1
    EXECUTION_STATUS_COMPLETED: _ExecutionStatus.ValueType  # 2
    EXECUTION_STATUS_FAILED: _ExecutionStatus.ValueType  # 3
    EXECUTION_STATUS_CANCELLED: _ExecutionStatus.ValueType  # 4
    EXECUTION_STATUS_PAUSED: _ExecutionStatus.ValueType  # 5
    EXECUTION_STATUS_RECOVERY_FAILED: _ExecutionStatus.ValueType  # 6

class ExecutionStatus(_ExecutionStatus, metaclass=_ExecutionStatusEnumTypeWrapper):
    """=============================================================================
    Status enums
    =============================================================================

    Execution status for runs, items, and steps.
    """

EXECUTION_STATUS_UNSPECIFIED: ExecutionStatus.ValueType  # 0
EXECUTION_STATUS_RUNNING: ExecutionStatus.ValueType  # 1
EXECUTION_STATUS_COMPLETED: ExecutionStatus.ValueType  # 2
EXECUTION_STATUS_FAILED: ExecutionStatus.ValueType  # 3
EXECUTION_STATUS_CANCELLED: ExecutionStatus.ValueType  # 4
EXECUTION_STATUS_PAUSED: ExecutionStatus.ValueType  # 5
EXECUTION_STATUS_RECOVERY_FAILED: ExecutionStatus.ValueType  # 6
Global___ExecutionStatus: typing_extensions.TypeAlias = ExecutionStatus

class _ResultOrder:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ResultOrderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResultOrder.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESULT_ORDER_UNSPECIFIED: _ResultOrder.ValueType  # 0
    RESULT_ORDER_BY_INDEX: _ResultOrder.ValueType  # 1
    """Order results by their index in the input array (default)."""
    RESULT_ORDER_BY_COMPLETION: _ResultOrder.ValueType  # 2
    """Order results by completion time."""

class ResultOrder(_ResultOrder, metaclass=_ResultOrderEnumTypeWrapper):
    """Result ordering for item results."""

RESULT_ORDER_UNSPECIFIED: ResultOrder.ValueType  # 0
RESULT_ORDER_BY_INDEX: ResultOrder.ValueType  # 1
"""Order results by their index in the input array (default)."""
RESULT_ORDER_BY_COMPLETION: ResultOrder.ValueType  # 2
"""Order results by completion time."""
Global___ResultOrder: typing_extensions.TypeAlias = ResultOrder

@typing.final
class ObservabilityContext(google.protobuf.message.Message):
    """=============================================================================
    Observability
    =============================================================================

    Observability context for distributed tracing and logging.

    Passed with protocol requests to enable trace correlation and structured
    logging across the Stepflow runtime and component servers.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRACE_ID_FIELD_NUMBER: builtins.int
    SPAN_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    FLOW_ID_FIELD_NUMBER: builtins.int
    STEP_ID_FIELD_NUMBER: builtins.int
    trace_id: builtins.str
    """OpenTelemetry trace ID (128-bit, hex encoded).
    Present when tracing is enabled.
    """
    span_id: builtins.str
    """OpenTelemetry span ID (64-bit, hex encoded).
    Component servers should use this as the parent span.
    """
    run_id: builtins.str
    """The ID of the workflow run (UUID).
    Present for workflow execution requests, absent for discovery.
    """
    flow_id: builtins.str
    """The ID of the flow being executed (SHA-256 blob hash).
    Present for workflow execution requests, absent for discovery.
    """
    step_id: builtins.str
    """The ID of the step being executed.
    Present for step-level execution, absent for workflow-level operations.
    """
    def __init__(
        self,
        *,
        trace_id: builtins.str | None = ...,
        span_id: builtins.str | None = ...,
        run_id: builtins.str | None = ...,
        flow_id: builtins.str | None = ...,
        step_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_flow_id", b"_flow_id", "_run_id", b"_run_id", "_span_id", b"_span_id", "_step_id", b"_step_id", "_trace_id", b"_trace_id", "flow_id", b"flow_id", "run_id", b"run_id", "span_id", b"span_id", "step_id", b"step_id", "trace_id", b"trace_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_flow_id", b"_flow_id", "_run_id", b"_run_id", "_span_id", b"_span_id", "_step_id", b"_step_id", "_trace_id", b"_trace_id", "flow_id", b"flow_id", "run_id", b"run_id", "span_id", b"span_id", "step_id", b"step_id", "trace_id", b"trace_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_flow_id", b"_flow_id"]) -> typing.Literal["flow_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_run_id", b"_run_id"]) -> typing.Literal["run_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_span_id", b"_span_id"]) -> typing.Literal["span_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_step_id", b"_step_id"]) -> typing.Literal["step_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_trace_id", b"_trace_id"]) -> typing.Literal["trace_id"] | None: ...

Global___ObservabilityContext: typing_extensions.TypeAlias = ObservabilityContext

@typing.final
class ItemStatistics(google.protobuf.message.Message):
    """=============================================================================
    Shared types used across services
    =============================================================================

    Aggregate statistics for items in a run.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOTAL_FIELD_NUMBER: builtins.int
    COMPLETED_FIELD_NUMBER: builtins.int
    RUNNING_FIELD_NUMBER: builtins.int
    FAILED_FIELD_NUMBER: builtins.int
    CANCELLED_FIELD_NUMBER: builtins.int
    total: builtins.int
    completed: builtins.int
    running: builtins.int
    failed: builtins.int
    cancelled: builtins.int
    def __init__(
        self,
        *,
        total: builtins.int = ...,
        completed: builtins.int = ...,
        running: builtins.int = ...,
        failed: builtins.int = ...,
        cancelled: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cancelled", b"cancelled", "completed", b"completed", "failed", b"failed", "running", b"running", "total", b"total"]) -> None: ...

Global___ItemStatistics: typing_extensions.TypeAlias = ItemStatistics

@typing.final
class ItemResult(google.protobuf.message.Message):
    """Result of a single item in a run."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEM_INDEX_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    OUTPUT_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    COMPLETED_AT_FIELD_NUMBER: builtins.int
    item_index: builtins.int
    """Index of this item in the input array (0-based)."""
    status: Global___ExecutionStatus.ValueType
    """Execution status of this item."""
    error_message: builtins.str
    """Error message (present when failed)."""
    error_code: builtins.int
    """Error code (present when failed)."""
    @property
    def output(self) -> google.protobuf.struct_pb2.Value:
        """Result of this item (present when completed successfully)."""

    @property
    def completed_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """When this item completed."""

    def __init__(
        self,
        *,
        item_index: builtins.int = ...,
        status: Global___ExecutionStatus.ValueType = ...,
        output: google.protobuf.struct_pb2.Value | None = ...,
        error_message: builtins.str | None = ...,
        error_code: builtins.int | None = ...,
        completed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_completed_at", b"_completed_at", "_error_code", b"_error_code", "_error_message", b"_error_message", "_output", b"_output", "completed_at", b"completed_at", "error_code", b"error_code", "error_message", b"error_message", "output", b"output"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_completed_at", b"_completed_at", "_error_code", b"_error_code", "_error_message", b"_error_message", "_output", b"_output", "completed_at", b"completed_at", "error_code", b"error_code", "error_message", b"error_message", "item_index", b"item_index", "output", b"output", "status", b"status"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_completed_at", b"_completed_at"]) -> typing.Literal["completed_at"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_error_code", b"_error_code"]) -> typing.Literal["error_code"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_error_message", b"_error_message"]) -> typing.Literal["error_message"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_output", b"_output"]) -> typing.Literal["output"] | None: ...

Global___ItemResult: typing_extensions.TypeAlias = ItemResult
