"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ListRegisteredComponentsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXCLUDE_SCHEMAS_FIELD_NUMBER: builtins.int
    exclude_schemas: builtins.bool
    """Set to true to exclude input/output schemas from the response.
    By default (when false or omitted), schemas are included.
    """
    def __init__(
        self,
        *,
        exclude_schemas: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["exclude_schemas", b"exclude_schemas"]) -> None: ...

Global___ListRegisteredComponentsRequest: typing_extensions.TypeAlias = ListRegisteredComponentsRequest

@typing.final
class ListRegisteredComponentsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMPONENTS_FIELD_NUMBER: builtins.int
    COMPLETE_FIELD_NUMBER: builtins.int
    FAILED_PLUGINS_FIELD_NUMBER: builtins.int
    complete: builtins.bool
    """True if all plugins responded successfully. When false, the component
    list is partial — see `failed_plugins` for details.
    """
    @property
    def components(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ComponentInfoEntry]:
        """All available components, sorted by name.
        When some plugins fail discovery, this contains components from the
        plugins that succeeded — check `complete` and `failed_plugins`.
        """

    @property
    def failed_plugins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PluginDiscoveryError]:
        """Plugins that failed component discovery (empty when complete is true)."""

    def __init__(
        self,
        *,
        components: collections.abc.Iterable[Global___ComponentInfoEntry] | None = ...,
        complete: builtins.bool = ...,
        failed_plugins: collections.abc.Iterable[Global___PluginDiscoveryError] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["complete", b"complete", "components", b"components", "failed_plugins", b"failed_plugins"]) -> None: ...

Global___ListRegisteredComponentsResponse: typing_extensions.TypeAlias = ListRegisteredComponentsResponse

@typing.final
class PluginDiscoveryError(google.protobuf.message.Message):
    """A plugin that failed during component discovery."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLUGIN_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    plugin: builtins.str
    """Plugin name from the orchestrator config (e.g., "python", "node")."""
    error: builtins.str
    """Human-readable error message."""
    def __init__(
        self,
        *,
        plugin: builtins.str = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "plugin", b"plugin"]) -> None: ...

Global___PluginDiscoveryError: typing_extensions.TypeAlias = PluginDiscoveryError

@typing.final
class ComponentInfoEntry(google.protobuf.message.Message):
    """A component registered with the orchestrator."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMPONENT_ID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    INPUT_SCHEMA_FIELD_NUMBER: builtins.int
    OUTPUT_SCHEMA_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    PLUGIN_FIELD_NUMBER: builtins.int
    component_id: builtins.str
    """Unique component identifier within its plugin (e.g., "openai", "my_func")."""
    description: builtins.str
    """Optional human-readable description."""
    path: builtins.str
    """Path pattern this component is registered at (e.g., "/openai", "/my_func").
    Combined with the route prefix to form the full path (e.g., "/builtin/openai").
    """
    plugin: builtins.str
    """The plugin that provides this component (e.g., "builtin", "python")."""
    @property
    def input_schema(self) -> google.protobuf.struct_pb2.Struct:
        """JSON Schema for the component's input (null if schemas not requested)."""

    @property
    def output_schema(self) -> google.protobuf.struct_pb2.Struct:
        """JSON Schema for the component's output (null if schemas not requested)."""

    def __init__(
        self,
        *,
        component_id: builtins.str = ...,
        description: builtins.str | None = ...,
        input_schema: google.protobuf.struct_pb2.Struct | None = ...,
        output_schema: google.protobuf.struct_pb2.Struct | None = ...,
        path: builtins.str = ...,
        plugin: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_description", b"_description", "_input_schema", b"_input_schema", "_output_schema", b"_output_schema", "description", b"description", "input_schema", b"input_schema", "output_schema", b"output_schema"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_description", b"_description", "_input_schema", b"_input_schema", "_output_schema", b"_output_schema", "component_id", b"component_id", "description", b"description", "input_schema", b"input_schema", "output_schema", b"output_schema", "path", b"path", "plugin", b"plugin"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_input_schema", b"_input_schema"]) -> typing.Literal["input_schema"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_output_schema", b"_output_schema"]) -> typing.Literal["output_schema"] | None: ...

Global___ComponentInfoEntry: typing_extensions.TypeAlias = ComponentInfoEntry
