"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

import abc
import collections.abc
import grpc
import grpc.aio
from . import flows_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_FlowsServiceStoreFlowType = typing_extensions.TypeVar(
    '_FlowsServiceStoreFlowType',
    grpc.UnaryUnaryMultiCallable[
        flows_pb2.StoreFlowRequest,
        flows_pb2.StoreFlowResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        flows_pb2.StoreFlowRequest,
        flows_pb2.StoreFlowResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        flows_pb2.StoreFlowRequest,
        flows_pb2.StoreFlowResponse,
    ],
)

_FlowsServiceGetFlowType = typing_extensions.TypeVar(
    '_FlowsServiceGetFlowType',
    grpc.UnaryUnaryMultiCallable[
        flows_pb2.GetFlowRequest,
        flows_pb2.GetFlowResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        flows_pb2.GetFlowRequest,
        flows_pb2.GetFlowResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        flows_pb2.GetFlowRequest,
        flows_pb2.GetFlowResponse,
    ],
)

_FlowsServiceDeleteFlowType = typing_extensions.TypeVar(
    '_FlowsServiceDeleteFlowType',
    grpc.UnaryUnaryMultiCallable[
        flows_pb2.DeleteFlowRequest,
        flows_pb2.DeleteFlowResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        flows_pb2.DeleteFlowRequest,
        flows_pb2.DeleteFlowResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        flows_pb2.DeleteFlowRequest,
        flows_pb2.DeleteFlowResponse,
    ],
)

_FlowsServiceGetFlowVariablesType = typing_extensions.TypeVar(
    '_FlowsServiceGetFlowVariablesType',
    grpc.UnaryUnaryMultiCallable[
        flows_pb2.GetFlowVariablesRequest,
        flows_pb2.GetFlowVariablesResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        flows_pb2.GetFlowVariablesRequest,
        flows_pb2.GetFlowVariablesResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        flows_pb2.GetFlowVariablesRequest,
        flows_pb2.GetFlowVariablesResponse,
    ],
)

class FlowsServiceStub(typing.Generic[_FlowsServiceStoreFlowType, _FlowsServiceGetFlowType, _FlowsServiceDeleteFlowType, _FlowsServiceGetFlowVariablesType]):
    """Service for managing workflow (flow) definitions."""

    @typing.overload
    def __init__(self: FlowsServiceStub[
        grpc.UnaryUnaryMultiCallable[
            flows_pb2.StoreFlowRequest,
            flows_pb2.StoreFlowResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            flows_pb2.GetFlowRequest,
            flows_pb2.GetFlowResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            flows_pb2.DeleteFlowRequest,
            flows_pb2.DeleteFlowResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            flows_pb2.GetFlowVariablesRequest,
            flows_pb2.GetFlowVariablesResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: FlowsServiceStub[
        grpc.aio.UnaryUnaryMultiCallable[
            flows_pb2.StoreFlowRequest,
            flows_pb2.StoreFlowResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            flows_pb2.GetFlowRequest,
            flows_pb2.GetFlowResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            flows_pb2.DeleteFlowRequest,
            flows_pb2.DeleteFlowResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            flows_pb2.GetFlowVariablesRequest,
            flows_pb2.GetFlowVariablesResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    StoreFlow: _FlowsServiceStoreFlowType
    """Store a flow definition and return its content-based ID.

    Validates the workflow and returns diagnostics. When `dry_run` is true,
    the flow is validated but not stored. If validation produces fatal
    diagnostics, the flow is not stored even when `dry_run` is false.
    """

    GetFlow: _FlowsServiceGetFlowType
    """Retrieve a flow definition by its blob ID."""

    DeleteFlow: _FlowsServiceDeleteFlowType
    """Delete a flow definition by its blob ID."""

    GetFlowVariables: _FlowsServiceGetFlowVariablesType
    """Get the variable definitions for a flow.

    Lightweight endpoint that returns variable schema and environment
    variable mappings without fetching the entire flow definition.
    """

FlowsServiceAsyncStub: typing_extensions.TypeAlias = FlowsServiceStub[
    grpc.aio.UnaryUnaryMultiCallable[
        flows_pb2.StoreFlowRequest,
        flows_pb2.StoreFlowResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        flows_pb2.GetFlowRequest,
        flows_pb2.GetFlowResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        flows_pb2.DeleteFlowRequest,
        flows_pb2.DeleteFlowResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        flows_pb2.GetFlowVariablesRequest,
        flows_pb2.GetFlowVariablesResponse,
    ],
]

class FlowsServiceServicer(metaclass=abc.ABCMeta):
    """Service for managing workflow (flow) definitions."""

    @abc.abstractmethod
    def StoreFlow(
        self,
        request: flows_pb2.StoreFlowRequest,
        context: _ServicerContext,
    ) -> typing.Union[flows_pb2.StoreFlowResponse, collections.abc.Awaitable[flows_pb2.StoreFlowResponse]]:
        """Store a flow definition and return its content-based ID.

        Validates the workflow and returns diagnostics. When `dry_run` is true,
        the flow is validated but not stored. If validation produces fatal
        diagnostics, the flow is not stored even when `dry_run` is false.
        """

    @abc.abstractmethod
    def GetFlow(
        self,
        request: flows_pb2.GetFlowRequest,
        context: _ServicerContext,
    ) -> typing.Union[flows_pb2.GetFlowResponse, collections.abc.Awaitable[flows_pb2.GetFlowResponse]]:
        """Retrieve a flow definition by its blob ID."""

    @abc.abstractmethod
    def DeleteFlow(
        self,
        request: flows_pb2.DeleteFlowRequest,
        context: _ServicerContext,
    ) -> typing.Union[flows_pb2.DeleteFlowResponse, collections.abc.Awaitable[flows_pb2.DeleteFlowResponse]]:
        """Delete a flow definition by its blob ID."""

    @abc.abstractmethod
    def GetFlowVariables(
        self,
        request: flows_pb2.GetFlowVariablesRequest,
        context: _ServicerContext,
    ) -> typing.Union[flows_pb2.GetFlowVariablesResponse, collections.abc.Awaitable[flows_pb2.GetFlowVariablesResponse]]:
        """Get the variable definitions for a flow.

        Lightweight endpoint that returns variable schema and environment
        variable mappings without fetching the entire flow definition.
        """

def add_FlowsServiceServicer_to_server(servicer: FlowsServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
