"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HealthCheckRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___HealthCheckRequest: typing_extensions.TypeAlias = HealthCheckRequest

@typing.final
class HealthCheckResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    BUILD_FIELD_NUMBER: builtins.int
    status: builtins.str
    """Service status (e.g., "healthy")."""
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp when health was checked."""

    @property
    def build(self) -> Global___BuildInfo:
        """Build metadata for the running service."""

    def __init__(
        self,
        *,
        status: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        build: Global___BuildInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["build", b"build", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["build", b"build", "status", b"status", "timestamp", b"timestamp"]) -> None: ...

Global___HealthCheckResponse: typing_extensions.TypeAlias = HealthCheckResponse

@typing.final
class BuildInfo(google.protobuf.message.Message):
    """Build-time metadata embedded in the service binary."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GIT_VERSION_FIELD_NUMBER: builtins.int
    DIRTY_FIELD_NUMBER: builtins.int
    RUSTC_VERSION_FIELD_NUMBER: builtins.int
    PROFILE_FIELD_NUMBER: builtins.int
    FEATURES_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    git_version: builtins.str
    """Git version string from `git describe --tags`. Returns the tag name
    if HEAD is tagged (e.g., "v0.11.0"), otherwise "tag-N-gSHORTHASH"
    (e.g., "v0.11.0-3-gabcdef1"). Falls back to the short commit hash
    if no tags exist.
    """
    dirty: builtins.bool
    """True if the working tree had uncommitted changes at build time."""
    rustc_version: builtins.str
    """Rust compiler version (e.g., "1.82.0")."""
    profile: builtins.str
    """Build profile (e.g., "debug" or "release")."""
    target: builtins.str
    """Target architecture (e.g., "aarch64-apple-darwin")."""
    @property
    def features(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Cargo features enabled at build time."""

    def __init__(
        self,
        *,
        git_version: builtins.str = ...,
        dirty: builtins.bool = ...,
        rustc_version: builtins.str = ...,
        profile: builtins.str = ...,
        features: collections.abc.Iterable[builtins.str] | None = ...,
        target: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dirty", b"dirty", "features", b"features", "git_version", b"git_version", "profile", b"profile", "rustc_version", b"rustc_version", "target", b"target"]) -> None: ...

Global___BuildInfo: typing_extensions.TypeAlias = BuildInfo
