"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

import abc
import collections.abc
import grpc
import grpc.aio
from . import health_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_HealthServiceHealthCheckType = typing_extensions.TypeVar(
    '_HealthServiceHealthCheckType',
    grpc.UnaryUnaryMultiCallable[
        health_pb2.HealthCheckRequest,
        health_pb2.HealthCheckResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        health_pb2.HealthCheckRequest,
        health_pb2.HealthCheckResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        health_pb2.HealthCheckRequest,
        health_pb2.HealthCheckResponse,
    ],
)

class HealthServiceStub(typing.Generic[_HealthServiceHealthCheckType]):
    """Service health check endpoint."""

    @typing.overload
    def __init__(self: HealthServiceStub[
        grpc.UnaryUnaryMultiCallable[
            health_pb2.HealthCheckRequest,
            health_pb2.HealthCheckResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: HealthServiceStub[
        grpc.aio.UnaryUnaryMultiCallable[
            health_pb2.HealthCheckRequest,
            health_pb2.HealthCheckResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    HealthCheck: _HealthServiceHealthCheckType
    """Check service health and return status, version, and timestamp."""

HealthServiceAsyncStub: typing_extensions.TypeAlias = HealthServiceStub[
    grpc.aio.UnaryUnaryMultiCallable[
        health_pb2.HealthCheckRequest,
        health_pb2.HealthCheckResponse,
    ],
]

class HealthServiceServicer(metaclass=abc.ABCMeta):
    """Service health check endpoint."""

    @abc.abstractmethod
    def HealthCheck(
        self,
        request: health_pb2.HealthCheckRequest,
        context: _ServicerContext,
    ) -> typing.Union[health_pb2.HealthCheckResponse, collections.abc.Awaitable[health_pb2.HealthCheckResponse]]:
        """Check service health and return status, version, and timestamp."""

def add_HealthServiceServicer_to_server(servicer: HealthServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
