"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

import abc
import collections.abc
import grpc
import grpc.aio
from . import orchestrator_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_OrchestratorServiceSubmitRunType = typing_extensions.TypeVar(
    '_OrchestratorServiceSubmitRunType',
    grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.OrchestratorSubmitRunRequest,
        orchestrator_pb2.OrchestratorRunStatus,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.OrchestratorSubmitRunRequest,
        orchestrator_pb2.OrchestratorRunStatus,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.OrchestratorSubmitRunRequest,
        orchestrator_pb2.OrchestratorRunStatus,
    ],
)

_OrchestratorServiceGetRunType = typing_extensions.TypeVar(
    '_OrchestratorServiceGetRunType',
    grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.OrchestratorGetRunRequest,
        orchestrator_pb2.OrchestratorRunStatus,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.OrchestratorGetRunRequest,
        orchestrator_pb2.OrchestratorRunStatus,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.OrchestratorGetRunRequest,
        orchestrator_pb2.OrchestratorRunStatus,
    ],
)

_OrchestratorServiceCompleteTaskType = typing_extensions.TypeVar(
    '_OrchestratorServiceCompleteTaskType',
    grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.CompleteTaskRequest,
        orchestrator_pb2.CompleteTaskResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.CompleteTaskRequest,
        orchestrator_pb2.CompleteTaskResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.CompleteTaskRequest,
        orchestrator_pb2.CompleteTaskResponse,
    ],
)

_OrchestratorServiceStartTaskType = typing_extensions.TypeVar(
    '_OrchestratorServiceStartTaskType',
    grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.StartTaskRequest,
        orchestrator_pb2.StartTaskResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.StartTaskRequest,
        orchestrator_pb2.StartTaskResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.StartTaskRequest,
        orchestrator_pb2.StartTaskResponse,
    ],
)

_OrchestratorServiceTaskHeartbeatType = typing_extensions.TypeVar(
    '_OrchestratorServiceTaskHeartbeatType',
    grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.TaskHeartbeatRequest,
        orchestrator_pb2.TaskHeartbeatResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.TaskHeartbeatRequest,
        orchestrator_pb2.TaskHeartbeatResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        orchestrator_pb2.TaskHeartbeatRequest,
        orchestrator_pb2.TaskHeartbeatResponse,
    ],
)

class OrchestratorServiceStub(typing.Generic[_OrchestratorServiceSubmitRunType, _OrchestratorServiceGetRunType, _OrchestratorServiceCompleteTaskType, _OrchestratorServiceStartTaskType, _OrchestratorServiceTaskHeartbeatType]):
    """Service exposed by the orchestrator for workers to interact with during
    component execution. Workers reach this via `orchestrator_service_url`
    from TaskContext.

    This must reach the orchestrator that owns the specific run — it is NOT
    interchangeable with other orchestrators (unlike WorkerService).

    gRPC only — not exposed as REST.
    """

    @typing.overload
    def __init__(self: OrchestratorServiceStub[
        grpc.UnaryUnaryMultiCallable[
            orchestrator_pb2.OrchestratorSubmitRunRequest,
            orchestrator_pb2.OrchestratorRunStatus,
        ],
        grpc.UnaryUnaryMultiCallable[
            orchestrator_pb2.OrchestratorGetRunRequest,
            orchestrator_pb2.OrchestratorRunStatus,
        ],
        grpc.UnaryUnaryMultiCallable[
            orchestrator_pb2.CompleteTaskRequest,
            orchestrator_pb2.CompleteTaskResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            orchestrator_pb2.StartTaskRequest,
            orchestrator_pb2.StartTaskResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            orchestrator_pb2.TaskHeartbeatRequest,
            orchestrator_pb2.TaskHeartbeatResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: OrchestratorServiceStub[
        grpc.aio.UnaryUnaryMultiCallable[
            orchestrator_pb2.OrchestratorSubmitRunRequest,
            orchestrator_pb2.OrchestratorRunStatus,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            orchestrator_pb2.OrchestratorGetRunRequest,
            orchestrator_pb2.OrchestratorRunStatus,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            orchestrator_pb2.CompleteTaskRequest,
            orchestrator_pb2.CompleteTaskResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            orchestrator_pb2.StartTaskRequest,
            orchestrator_pb2.StartTaskResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            orchestrator_pb2.TaskHeartbeatRequest,
            orchestrator_pb2.TaskHeartbeatResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    SubmitRun: _OrchestratorServiceSubmitRunType
    """Submit a sub-flow run from within a component execution."""

    GetRun: _OrchestratorServiceGetRunType
    """Get the status of a run (optionally waiting for completion)."""

    CompleteTask: _OrchestratorServiceCompleteTaskType
    """Report task completion (success or failure).

    Called by workers after executing a component, regardless of how the
    task was received (PullTasks, NATS, Kafka, etc.). The worker uses the
    `orchestrator_service_url` from the task's TaskContext to reach
    the orchestrator that owns the run.
    """

    StartTask: _OrchestratorServiceStartTaskType
    """Notify the orchestrator that the worker has started executing a task.

    Called by the worker immediately before beginning component execution.
    This transitions the task from "queued" to "executing" on the
    orchestrator side, starting the heartbeat timeout. If the response
    has `timed_out = true`, the task already expired in the queue and the
    worker should skip execution.
    """

    TaskHeartbeat: _OrchestratorServiceTaskHeartbeatType
    """Send a heartbeat for an in-progress task.

    Called periodically by the worker during component execution (typically
    every 1s). Each heartbeat resets the crash-detection timer on the
    orchestrator. If heartbeats stop arriving for 5s, the orchestrator
    presumes the worker crashed and fails the task.
    """

OrchestratorServiceAsyncStub: typing_extensions.TypeAlias = OrchestratorServiceStub[
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.OrchestratorSubmitRunRequest,
        orchestrator_pb2.OrchestratorRunStatus,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.OrchestratorGetRunRequest,
        orchestrator_pb2.OrchestratorRunStatus,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.CompleteTaskRequest,
        orchestrator_pb2.CompleteTaskResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.StartTaskRequest,
        orchestrator_pb2.StartTaskResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        orchestrator_pb2.TaskHeartbeatRequest,
        orchestrator_pb2.TaskHeartbeatResponse,
    ],
]

class OrchestratorServiceServicer(metaclass=abc.ABCMeta):
    """Service exposed by the orchestrator for workers to interact with during
    component execution. Workers reach this via `orchestrator_service_url`
    from TaskContext.

    This must reach the orchestrator that owns the specific run — it is NOT
    interchangeable with other orchestrators (unlike WorkerService).

    gRPC only — not exposed as REST.
    """

    @abc.abstractmethod
    def SubmitRun(
        self,
        request: orchestrator_pb2.OrchestratorSubmitRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.OrchestratorRunStatus, collections.abc.Awaitable[orchestrator_pb2.OrchestratorRunStatus]]:
        """Submit a sub-flow run from within a component execution."""

    @abc.abstractmethod
    def GetRun(
        self,
        request: orchestrator_pb2.OrchestratorGetRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.OrchestratorRunStatus, collections.abc.Awaitable[orchestrator_pb2.OrchestratorRunStatus]]:
        """Get the status of a run (optionally waiting for completion)."""

    @abc.abstractmethod
    def CompleteTask(
        self,
        request: orchestrator_pb2.CompleteTaskRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.CompleteTaskResponse, collections.abc.Awaitable[orchestrator_pb2.CompleteTaskResponse]]:
        """Report task completion (success or failure).

        Called by workers after executing a component, regardless of how the
        task was received (PullTasks, NATS, Kafka, etc.). The worker uses the
        `orchestrator_service_url` from the task's TaskContext to reach
        the orchestrator that owns the run.
        """

    @abc.abstractmethod
    def StartTask(
        self,
        request: orchestrator_pb2.StartTaskRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.StartTaskResponse, collections.abc.Awaitable[orchestrator_pb2.StartTaskResponse]]:
        """Notify the orchestrator that the worker has started executing a task.

        Called by the worker immediately before beginning component execution.
        This transitions the task from "queued" to "executing" on the
        orchestrator side, starting the heartbeat timeout. If the response
        has `timed_out = true`, the task already expired in the queue and the
        worker should skip execution.
        """

    @abc.abstractmethod
    def TaskHeartbeat(
        self,
        request: orchestrator_pb2.TaskHeartbeatRequest,
        context: _ServicerContext,
    ) -> typing.Union[orchestrator_pb2.TaskHeartbeatResponse, collections.abc.Awaitable[orchestrator_pb2.TaskHeartbeatResponse]]:
        """Send a heartbeat for an in-progress task.

        Called periodically by the worker during component execution (typically
        every 1s). Each heartbeat resets the crash-detection timer on the
        orchestrator. If heartbeats stop arriving for 5s, the orchestrator
        presumes the worker crashed and fails the task.
        """

def add_OrchestratorServiceServicer_to_server(servicer: OrchestratorServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
