"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from . import common_pb2 as _common_pb2
from . import runs_pb2 as _runs_pb2
from . import tasks_pb2 as _tasks_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _TaskErrorCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TaskErrorCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TaskErrorCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TASK_ERROR_CODE_UNSPECIFIED: _TaskErrorCode.ValueType  # 0
    """Default value; should not be used explicitly."""
    TASK_ERROR_CODE_INTERNAL: _TaskErrorCode.ValueType  # 1
    """An unexpected internal error in the worker or runtime (e.g., serialization
    failure, panic, OOM). Generally not retriable without a fix.
    """
    TASK_ERROR_CODE_TIMEOUT: _TaskErrorCode.ValueType  # 2
    """The task exceeded its execution deadline or heartbeat timeout. The
    orchestrator may retry depending on the configured retry policy.
    """
    TASK_ERROR_CODE_INVALID_INPUT: _TaskErrorCode.ValueType  # 3
    """The component rejected its input (e.g., missing required fields, schema
    validation failure). Not retriable without correcting the input.
    """
    TASK_ERROR_CODE_COMPONENT_FAILED: _TaskErrorCode.ValueType  # 4
    """The component executed but returned a business-logic failure (e.g., an API
    call returned an error, a transformation produced an invalid result).
    """
    TASK_ERROR_CODE_CANCELLED: _TaskErrorCode.ValueType  # 5
    """The task was explicitly cancelled by the orchestrator (e.g., run
    cancellation, step timeout policy). Not retriable.
    """
    TASK_ERROR_CODE_UNAVAILABLE: _TaskErrorCode.ValueType  # 6
    """The worker or component could not be reached (e.g., worker disconnected,
    gRPC channel broken). Typically retriable after backoff.
    """

class TaskErrorCode(_TaskErrorCode, metaclass=_TaskErrorCodeEnumTypeWrapper):
    """--- CompleteTask ---

    Error codes for task failures.
    """

TASK_ERROR_CODE_UNSPECIFIED: TaskErrorCode.ValueType  # 0
"""Default value; should not be used explicitly."""
TASK_ERROR_CODE_INTERNAL: TaskErrorCode.ValueType  # 1
"""An unexpected internal error in the worker or runtime (e.g., serialization
failure, panic, OOM). Generally not retriable without a fix.
"""
TASK_ERROR_CODE_TIMEOUT: TaskErrorCode.ValueType  # 2
"""The task exceeded its execution deadline or heartbeat timeout. The
orchestrator may retry depending on the configured retry policy.
"""
TASK_ERROR_CODE_INVALID_INPUT: TaskErrorCode.ValueType  # 3
"""The component rejected its input (e.g., missing required fields, schema
validation failure). Not retriable without correcting the input.
"""
TASK_ERROR_CODE_COMPONENT_FAILED: TaskErrorCode.ValueType  # 4
"""The component executed but returned a business-logic failure (e.g., an API
call returned an error, a transformation produced an invalid result).
"""
TASK_ERROR_CODE_CANCELLED: TaskErrorCode.ValueType  # 5
"""The task was explicitly cancelled by the orchestrator (e.g., run
cancellation, step timeout policy). Not retriable.
"""
TASK_ERROR_CODE_UNAVAILABLE: TaskErrorCode.ValueType  # 6
"""The worker or component could not be reached (e.g., worker disconnected,
gRPC channel broken). Typically retriable after backoff.
"""
Global___TaskErrorCode: _TypeAlias = TaskErrorCode  # noqa: Y015

@_typing.final
class OrchestratorSubmitRunRequest(_message.Message):
    """--- SubmitRun ---

    Submit a sub-flow run from within a component execution.
    Wraps the shared CreateRunRequest with an optional subflow deduplication key.
    """

    DESCRIPTOR: _descriptor.Descriptor

    RUN_REQUEST_FIELD_NUMBER: _builtins.int
    SUBFLOW_KEY_FIELD_NUMBER: _builtins.int
    subflow_key: _builtins.str
    """Deterministic key for subflow deduplication during recovery.
    When present, the orchestrator will return an existing run with the
    same key instead of creating a duplicate.
    """
    @_builtins.property
    def run_request(self) -> _runs_pb2.CreateRunRequest:
        """The run creation parameters (shared with RunsService.CreateRun)."""

    def __init__(
        self,
        *,
        run_request: _runs_pb2.CreateRunRequest | None = ...,
        subflow_key: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_subflow_key", b"_subflow_key", "run_request", b"run_request", "subflow_key", b"subflow_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_subflow_key", b"_subflow_key", "run_request", b"run_request", "subflow_key", b"subflow_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__subflow_key: _TypeAlias = _typing.Literal["subflow_key"]  # noqa: Y015
    _WhichOneofArgType__subflow_key: _TypeAlias = _typing.Literal["_subflow_key", b"_subflow_key"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__subflow_key) -> _WhichOneofReturnType__subflow_key | None: ...

Global___OrchestratorSubmitRunRequest: _TypeAlias = OrchestratorSubmitRunRequest  # noqa: Y015

@_typing.final
class OrchestratorGetRunRequest(_message.Message):
    """--- GetRun ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    WAIT_FIELD_NUMBER: _builtins.int
    INCLUDE_RESULTS_FIELD_NUMBER: _builtins.int
    RESULT_ORDER_FIELD_NUMBER: _builtins.int
    TIMEOUT_SECS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID) to query."""
    wait: _builtins.bool
    """If true, wait for the run to complete before responding."""
    include_results: _builtins.bool
    """If true, include item results in the response."""
    result_order: _common_pb2.ResultOrder.ValueType
    """Result ordering."""
    timeout_secs: _builtins.int
    """Maximum seconds to wait when wait=true (default 300)."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        wait: _builtins.bool = ...,
        include_results: _builtins.bool = ...,
        result_order: _common_pb2.ResultOrder.ValueType = ...,
        timeout_secs: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_timeout_secs", b"_timeout_secs", "timeout_secs", b"timeout_secs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_timeout_secs", b"_timeout_secs", "include_results", b"include_results", "result_order", b"result_order", "run_id", b"run_id", "timeout_secs", b"timeout_secs", "wait", b"wait"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__timeout_secs: _TypeAlias = _typing.Literal["timeout_secs"]  # noqa: Y015
    _WhichOneofArgType__timeout_secs: _TypeAlias = _typing.Literal["_timeout_secs", b"_timeout_secs"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timeout_secs) -> _WhichOneofReturnType__timeout_secs | None: ...

Global___OrchestratorGetRunRequest: _TypeAlias = OrchestratorGetRunRequest  # noqa: Y015

@_typing.final
class OrchestratorRunStatus(_message.Message):
    """--- Response ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    FLOW_ID_FIELD_NUMBER: _builtins.int
    FLOW_NAME_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    COMPLETED_AT_FIELD_NUMBER: _builtins.int
    RESULTS_FIELD_NUMBER: _builtins.int
    ROOT_RUN_ID_FIELD_NUMBER: _builtins.int
    PARENT_RUN_ID_FIELD_NUMBER: _builtins.int
    CREATED_AT_SEQNO_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    flow_id: _builtins.str
    flow_name: _builtins.str
    status: _common_pb2.ExecutionStatus.ValueType
    root_run_id: _builtins.str
    """Run hierarchy fields.
    Root run ID (UUID). For top-level runs, equals run_id.
    """
    parent_run_id: _builtins.str
    """Parent run ID (UUID). Present only for sub-flow runs."""
    created_at_seqno: _builtins.int
    """Journal sequence number of the run creation event."""
    @_builtins.property
    def items(self) -> _common_pb2.ItemStatistics: ...
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def completed_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ItemResult]: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        flow_id: _builtins.str = ...,
        flow_name: _builtins.str | None = ...,
        status: _common_pb2.ExecutionStatus.ValueType = ...,
        items: _common_pb2.ItemStatistics | None = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        completed_at: _timestamp_pb2.Timestamp | None = ...,
        results: _abc.Iterable[_common_pb2.ItemResult] | None = ...,
        root_run_id: _builtins.str = ...,
        parent_run_id: _builtins.str | None = ...,
        created_at_seqno: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at", "_flow_name", b"_flow_name", "_parent_run_id", b"_parent_run_id", "completed_at", b"completed_at", "created_at", b"created_at", "flow_name", b"flow_name", "items", b"items", "parent_run_id", b"parent_run_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at", "_flow_name", b"_flow_name", "_parent_run_id", b"_parent_run_id", "completed_at", b"completed_at", "created_at", b"created_at", "created_at_seqno", b"created_at_seqno", "flow_id", b"flow_id", "flow_name", b"flow_name", "items", b"items", "parent_run_id", b"parent_run_id", "results", b"results", "root_run_id", b"root_run_id", "run_id", b"run_id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__completed_at: _TypeAlias = _typing.Literal["completed_at"]  # noqa: Y015
    _WhichOneofArgType__completed_at: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at"]  # noqa: Y015
    _WhichOneofReturnType__flow_name: _TypeAlias = _typing.Literal["flow_name"]  # noqa: Y015
    _WhichOneofArgType__flow_name: _TypeAlias = _typing.Literal["_flow_name", b"_flow_name"]  # noqa: Y015
    _WhichOneofReturnType__parent_run_id: _TypeAlias = _typing.Literal["parent_run_id"]  # noqa: Y015
    _WhichOneofArgType__parent_run_id: _TypeAlias = _typing.Literal["_parent_run_id", b"_parent_run_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__completed_at) -> _WhichOneofReturnType__completed_at | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__flow_name) -> _WhichOneofReturnType__flow_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parent_run_id) -> _WhichOneofReturnType__parent_run_id | None: ...

Global___OrchestratorRunStatus: _TypeAlias = OrchestratorRunStatus  # noqa: Y015

@_typing.final
class TaskError(_message.Message):
    """Structured error type for task failures."""

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    code: Global___TaskErrorCode.ValueType
    """Error code categorizing the failure."""
    message: _builtins.str
    """Human-readable error message."""
    def __init__(
        self,
        *,
        code: Global___TaskErrorCode.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TaskError: _TypeAlias = TaskError  # noqa: Y015

@_typing.final
class CompleteTaskRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    RESPONSE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """The task ID from the TaskAssignment."""
    @_builtins.property
    def response(self) -> _tasks_pb2.ComponentExecuteResponse:
        """The component execution response (on success)."""

    @_builtins.property
    def error(self) -> Global___TaskError:
        """Structured error (on failure)."""

    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        response: _tasks_pb2.ComponentExecuteResponse | None = ...,
        error: Global___TaskError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "response", b"response", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "response", b"response", "result", b"result", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["response", "error"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___CompleteTaskRequest: _TypeAlias = CompleteTaskRequest  # noqa: Y015

@_typing.final
class CompleteTaskResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CompleteTaskResponse: _TypeAlias = CompleteTaskResponse  # noqa: Y015

@_typing.final
class StartTaskRequest(_message.Message):
    """--- StartTask ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """The task ID from the TaskAssignment."""
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartTaskRequest: _TypeAlias = StartTaskRequest  # noqa: Y015

@_typing.final
class StartTaskResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIMED_OUT_FIELD_NUMBER: _builtins.int
    timed_out: _builtins.bool
    """If true, the task already timed out in the queue before the worker
    called StartTask. The worker should skip execution — no CompleteTask
    call is needed.
    """
    def __init__(
        self,
        *,
        timed_out: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["timed_out", b"timed_out"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartTaskResponse: _TypeAlias = StartTaskResponse  # noqa: Y015

@_typing.final
class TaskHeartbeatRequest(_message.Message):
    """--- TaskHeartbeat ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    PROGRESS_FIELD_NUMBER: _builtins.int
    STATUS_MESSAGE_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """The task ID from the TaskAssignment."""
    progress: _builtins.float
    """Optional progress indicator (0.0 to 1.0)."""
    status_message: _builtins.str
    """Optional human-readable status message."""
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        progress: _builtins.float | None = ...,
        status_message: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_progress", b"_progress", "_status_message", b"_status_message", "progress", b"progress", "status_message", b"status_message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_progress", b"_progress", "_status_message", b"_status_message", "progress", b"progress", "status_message", b"status_message", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__progress: _TypeAlias = _typing.Literal["progress"]  # noqa: Y015
    _WhichOneofArgType__progress: _TypeAlias = _typing.Literal["_progress", b"_progress"]  # noqa: Y015
    _WhichOneofReturnType__status_message: _TypeAlias = _typing.Literal["status_message"]  # noqa: Y015
    _WhichOneofArgType__status_message: _TypeAlias = _typing.Literal["_status_message", b"_status_message"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__progress) -> _WhichOneofReturnType__progress | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status_message) -> _WhichOneofReturnType__status_message | None: ...

Global___TaskHeartbeatRequest: _TypeAlias = TaskHeartbeatRequest  # noqa: Y015

@_typing.final
class TaskHeartbeatResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SHOULD_CANCEL_FIELD_NUMBER: _builtins.int
    should_cancel: _builtins.bool
    """If true, the worker should cancel the task (e.g., run was cancelled)."""
    def __init__(
        self,
        *,
        should_cancel: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["should_cancel", b"should_cancel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TaskHeartbeatResponse: _TypeAlias = TaskHeartbeatResponse  # noqa: Y015
