"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
from . import common_pb2
from . import runs_pb2
from . import tasks_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TaskStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TaskStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TASK_STATUS_UNSPECIFIED: _TaskStatus.ValueType  # 0
    """Unspecified / default value."""
    TASK_STATUS_IN_PROGRESS: _TaskStatus.ValueType  # 1
    """Task is in progress — the calling worker owns it."""
    TASK_STATUS_ALREADY_CLAIMED: _TaskStatus.ValueType  # 2
    """Task is already being executed by a different worker.
    The calling worker should abort and not call CompleteTask.
    """
    TASK_STATUS_COMPLETED: _TaskStatus.ValueType  # 3
    """Task already has a result (completed or failed).
    The calling worker should abort.
    """
    TASK_STATUS_TIMED_OUT: _TaskStatus.ValueType  # 4
    """Task timed out in the queue before any worker claimed it.
    The calling worker should abort.
    """
    TASK_STATUS_NOT_FOUND: _TaskStatus.ValueType  # 5
    """Task ID not recognized — never existed or already cleaned up.
    The calling worker should abort.
    """

class TaskStatus(_TaskStatus, metaclass=_TaskStatusEnumTypeWrapper):
    """--- TaskHeartbeat ---

    Status of a task from the orchestrator's perspective.
    """

TASK_STATUS_UNSPECIFIED: TaskStatus.ValueType  # 0
"""Unspecified / default value."""
TASK_STATUS_IN_PROGRESS: TaskStatus.ValueType  # 1
"""Task is in progress — the calling worker owns it."""
TASK_STATUS_ALREADY_CLAIMED: TaskStatus.ValueType  # 2
"""Task is already being executed by a different worker.
The calling worker should abort and not call CompleteTask.
"""
TASK_STATUS_COMPLETED: TaskStatus.ValueType  # 3
"""Task already has a result (completed or failed).
The calling worker should abort.
"""
TASK_STATUS_TIMED_OUT: TaskStatus.ValueType  # 4
"""Task timed out in the queue before any worker claimed it.
The calling worker should abort.
"""
TASK_STATUS_NOT_FOUND: TaskStatus.ValueType  # 5
"""Task ID not recognized — never existed or already cleaned up.
The calling worker should abort.
"""
Global___TaskStatus: typing_extensions.TypeAlias = TaskStatus

@typing.final
class OrchestratorSubmitRunRequest(google.protobuf.message.Message):
    """--- SubmitRun ---

    Submit a sub-flow run from within a component execution.
    Wraps the shared CreateRunRequest with an optional subflow deduplication key.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_REQUEST_FIELD_NUMBER: builtins.int
    SUBFLOW_KEY_FIELD_NUMBER: builtins.int
    subflow_key: builtins.str
    """Deterministic key for subflow deduplication during recovery.
    When present, the orchestrator will return an existing run with the
    same key instead of creating a duplicate.
    """
    @property
    def run_request(self) -> runs_pb2.CreateRunRequest:
        """The run creation parameters (shared with RunsService.CreateRun)."""

    def __init__(
        self,
        *,
        run_request: runs_pb2.CreateRunRequest | None = ...,
        subflow_key: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_subflow_key", b"_subflow_key", "run_request", b"run_request", "subflow_key", b"subflow_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_subflow_key", b"_subflow_key", "run_request", b"run_request", "subflow_key", b"subflow_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_subflow_key", b"_subflow_key"]) -> typing.Literal["subflow_key"] | None: ...

Global___OrchestratorSubmitRunRequest: typing_extensions.TypeAlias = OrchestratorSubmitRunRequest

@typing.final
class OrchestratorGetRunRequest(google.protobuf.message.Message):
    """--- GetRun ---"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    WAIT_FIELD_NUMBER: builtins.int
    INCLUDE_RESULTS_FIELD_NUMBER: builtins.int
    RESULT_ORDER_FIELD_NUMBER: builtins.int
    TIMEOUT_SECS_FIELD_NUMBER: builtins.int
    run_id: builtins.str
    """Run ID (UUID) to query."""
    wait: builtins.bool
    """If true, wait for the run to complete before responding."""
    include_results: builtins.bool
    """If true, include item results in the response."""
    result_order: common_pb2.ResultOrder.ValueType
    """Result ordering."""
    timeout_secs: builtins.int
    """Maximum seconds to wait when wait=true (default 300)."""
    def __init__(
        self,
        *,
        run_id: builtins.str = ...,
        wait: builtins.bool = ...,
        include_results: builtins.bool = ...,
        result_order: common_pb2.ResultOrder.ValueType = ...,
        timeout_secs: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_timeout_secs", b"_timeout_secs", "timeout_secs", b"timeout_secs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_timeout_secs", b"_timeout_secs", "include_results", b"include_results", "result_order", b"result_order", "run_id", b"run_id", "timeout_secs", b"timeout_secs", "wait", b"wait"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_timeout_secs", b"_timeout_secs"]) -> typing.Literal["timeout_secs"] | None: ...

Global___OrchestratorGetRunRequest: typing_extensions.TypeAlias = OrchestratorGetRunRequest

@typing.final
class OrchestratorRunStatus(google.protobuf.message.Message):
    """--- Response ---"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    FLOW_ID_FIELD_NUMBER: builtins.int
    FLOW_NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    COMPLETED_AT_FIELD_NUMBER: builtins.int
    RESULTS_FIELD_NUMBER: builtins.int
    ROOT_RUN_ID_FIELD_NUMBER: builtins.int
    PARENT_RUN_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_SEQNO_FIELD_NUMBER: builtins.int
    run_id: builtins.str
    """Run ID (UUID)."""
    flow_id: builtins.str
    flow_name: builtins.str
    status: common_pb2.ExecutionStatus.ValueType
    root_run_id: builtins.str
    """Run hierarchy fields.
    Root run ID (UUID). For top-level runs, equals run_id.
    """
    parent_run_id: builtins.str
    """Parent run ID (UUID). Present only for sub-flow runs."""
    created_at_seqno: builtins.int
    """Journal sequence number of the run creation event."""
    @property
    def items(self) -> common_pb2.ItemStatistics: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def completed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common_pb2.ItemResult]: ...
    def __init__(
        self,
        *,
        run_id: builtins.str = ...,
        flow_id: builtins.str = ...,
        flow_name: builtins.str | None = ...,
        status: common_pb2.ExecutionStatus.ValueType = ...,
        items: common_pb2.ItemStatistics | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        completed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        results: collections.abc.Iterable[common_pb2.ItemResult] | None = ...,
        root_run_id: builtins.str = ...,
        parent_run_id: builtins.str | None = ...,
        created_at_seqno: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_completed_at", b"_completed_at", "_flow_name", b"_flow_name", "_parent_run_id", b"_parent_run_id", "completed_at", b"completed_at", "created_at", b"created_at", "flow_name", b"flow_name", "items", b"items", "parent_run_id", b"parent_run_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_completed_at", b"_completed_at", "_flow_name", b"_flow_name", "_parent_run_id", b"_parent_run_id", "completed_at", b"completed_at", "created_at", b"created_at", "created_at_seqno", b"created_at_seqno", "flow_id", b"flow_id", "flow_name", b"flow_name", "items", b"items", "parent_run_id", b"parent_run_id", "results", b"results", "root_run_id", b"root_run_id", "run_id", b"run_id", "status", b"status"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_completed_at", b"_completed_at"]) -> typing.Literal["completed_at"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_flow_name", b"_flow_name"]) -> typing.Literal["flow_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_parent_run_id", b"_parent_run_id"]) -> typing.Literal["parent_run_id"] | None: ...

Global___OrchestratorRunStatus: typing_extensions.TypeAlias = OrchestratorRunStatus

@typing.final
class TaskError(google.protobuf.message.Message):
    """--- CompleteTask ---

    Structured error type for task failures.
    TaskErrorCode is defined in common.proto.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    code: common_pb2.TaskErrorCode.ValueType
    """Error code categorizing the failure."""
    message: builtins.str
    """Human-readable error message."""
    @property
    def data(self) -> google.protobuf.struct_pb2.Struct:
        """Optional structured error data (stack traces, error context, etc.)."""

    def __init__(
        self,
        *,
        code: common_pb2.TaskErrorCode.ValueType = ...,
        message: builtins.str = ...,
        data: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_data", b"_data", "data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_data", b"_data", "code", b"code", "data", b"data", "message", b"message"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_data", b"_data"]) -> typing.Literal["data"] | None: ...

Global___TaskError: typing_extensions.TypeAlias = TaskError

@typing.final
class CompleteTaskRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    task_id: builtins.str
    """The task ID from the TaskAssignment."""
    @property
    def response(self) -> tasks_pb2.ComponentExecuteResponse:
        """The component execution response (on success)."""

    @property
    def error(self) -> Global___TaskError:
        """Structured error (on failure)."""

    def __init__(
        self,
        *,
        task_id: builtins.str = ...,
        response: tasks_pb2.ComponentExecuteResponse | None = ...,
        error: Global___TaskError | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "response", b"response", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "response", b"response", "result", b"result", "task_id", b"task_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["result", b"result"]) -> typing.Literal["response", "error"] | None: ...

Global___CompleteTaskRequest: typing_extensions.TypeAlias = CompleteTaskRequest

@typing.final
class CompleteTaskResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CompleteTaskResponse: typing_extensions.TypeAlias = CompleteTaskResponse

@typing.final
class TaskHeartbeatRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    WORKER_ID_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    STATUS_MESSAGE_FIELD_NUMBER: builtins.int
    task_id: builtins.str
    """The task ID from the TaskAssignment."""
    worker_id: builtins.str
    """Unique identifier for this worker instance. Must be stable for the
    duration of a task execution (same ID for start and all heartbeats).
    Used to detect duplicate task assignments — if a different worker_id
    sends a heartbeat for the same task, the response indicates
    ALREADY_CLAIMED.
    """
    progress: builtins.float
    """Optional progress indicator (0.0 to 1.0)."""
    status_message: builtins.str
    """Optional human-readable status message."""
    def __init__(
        self,
        *,
        task_id: builtins.str = ...,
        worker_id: builtins.str = ...,
        progress: builtins.float | None = ...,
        status_message: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_progress", b"_progress", "_status_message", b"_status_message", "progress", b"progress", "status_message", b"status_message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_progress", b"_progress", "_status_message", b"_status_message", "progress", b"progress", "status_message", b"status_message", "task_id", b"task_id", "worker_id", b"worker_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_progress", b"_progress"]) -> typing.Literal["progress"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_status_message", b"_status_message"]) -> typing.Literal["status_message"] | None: ...

Global___TaskHeartbeatRequest: typing_extensions.TypeAlias = TaskHeartbeatRequest

@typing.final
class TaskHeartbeatResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHOULD_ABORT_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    should_abort: builtins.bool
    """If true, the worker should abort execution of this task.
    Check `status` for the reason.
    """
    status: Global___TaskStatus.ValueType
    """Current task status from the orchestrator's perspective."""
    def __init__(
        self,
        *,
        should_abort: builtins.bool = ...,
        status: Global___TaskStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["should_abort", b"should_abort", "status", b"status"]) -> None: ...

Global___TaskHeartbeatResponse: typing_extensions.TypeAlias = TaskHeartbeatResponse
