"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from . import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateRunRequest(_message.Message):
    """--- CreateRun ---

    Shared run creation parameters used by both RunsService.CreateRun (REST/gRPC)
    and OrchestratorService.SubmitRun (worker callback for sub-flows).
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class VariablesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    FLOW_ID_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    OVERRIDES_FIELD_NUMBER: _builtins.int
    VARIABLES_FIELD_NUMBER: _builtins.int
    MAX_CONCURRENCY_FIELD_NUMBER: _builtins.int
    WAIT_FIELD_NUMBER: _builtins.int
    TIMEOUT_SECS_FIELD_NUMBER: _builtins.int
    flow_id: _builtins.str
    """Flow blob ID to execute."""
    max_concurrency: _builtins.int
    """Maximum concurrent item executions."""
    wait: _builtins.bool
    """If true, block until the run completes."""
    timeout_secs: _builtins.int
    """Maximum seconds to wait when wait=true (default 300)."""
    @_builtins.property
    def input(self) -> _containers.RepeatedCompositeFieldContainer[_struct_pb2.Value]:
        """Input data — one element per item (batch mode)."""

    @_builtins.property
    def overrides(self) -> _struct_pb2.Struct:
        """Workflow overrides to apply (JSON Merge Patch per step).
        Keys are step IDs, values are override objects.
        """

    @_builtins.property
    def variables(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Variables for variable references in the workflow."""

    def __init__(
        self,
        *,
        flow_id: _builtins.str = ...,
        input: _abc.Iterable[_struct_pb2.Value] | None = ...,
        overrides: _struct_pb2.Struct | None = ...,
        variables: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
        max_concurrency: _builtins.int | None = ...,
        wait: _builtins.bool = ...,
        timeout_secs: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_max_concurrency", b"_max_concurrency", "_overrides", b"_overrides", "_timeout_secs", b"_timeout_secs", "max_concurrency", b"max_concurrency", "overrides", b"overrides", "timeout_secs", b"timeout_secs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_max_concurrency", b"_max_concurrency", "_overrides", b"_overrides", "_timeout_secs", b"_timeout_secs", "flow_id", b"flow_id", "input", b"input", "max_concurrency", b"max_concurrency", "overrides", b"overrides", "timeout_secs", b"timeout_secs", "variables", b"variables", "wait", b"wait"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__max_concurrency: _TypeAlias = _typing.Literal["max_concurrency"]  # noqa: Y015
    _WhichOneofArgType__max_concurrency: _TypeAlias = _typing.Literal["_max_concurrency", b"_max_concurrency"]  # noqa: Y015
    _WhichOneofReturnType__overrides: _TypeAlias = _typing.Literal["overrides"]  # noqa: Y015
    _WhichOneofArgType__overrides: _TypeAlias = _typing.Literal["_overrides", b"_overrides"]  # noqa: Y015
    _WhichOneofReturnType__timeout_secs: _TypeAlias = _typing.Literal["timeout_secs"]  # noqa: Y015
    _WhichOneofArgType__timeout_secs: _TypeAlias = _typing.Literal["_timeout_secs", b"_timeout_secs"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_concurrency) -> _WhichOneofReturnType__max_concurrency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__overrides) -> _WhichOneofReturnType__overrides | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timeout_secs) -> _WhichOneofReturnType__timeout_secs | None: ...

Global___CreateRunRequest: _TypeAlias = CreateRunRequest  # noqa: Y015

@_typing.final
class CreateRunResponse(_message.Message):
    """Response for create run.

    The summary fields are included directly (not nested) to match the existing
    REST API's flattened JSON shape. tonic-rest serializes this as a flat object
    where RunSummary fields appear at the top level alongside `results`.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SUMMARY_FIELD_NUMBER: _builtins.int
    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def summary(self) -> Global___RunSummary:
        """Run summary."""

    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ItemResult]:
        """Item results, populated when wait=true and the run completed."""

    def __init__(
        self,
        *,
        summary: Global___RunSummary | None = ...,
        results: _abc.Iterable[_common_pb2.ItemResult] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results", "summary", b"summary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateRunResponse: _TypeAlias = CreateRunResponse  # noqa: Y015

@_typing.final
class ListRunsRequest(_message.Message):
    """--- ListRuns ---"""

    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    FLOW_NAME_FIELD_NUMBER: _builtins.int
    ROOT_RUN_ID_FIELD_NUMBER: _builtins.int
    PARENT_RUN_ID_FIELD_NUMBER: _builtins.int
    ROOTS_ONLY_FIELD_NUMBER: _builtins.int
    MAX_DEPTH_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    status: _common_pb2.ExecutionStatus.ValueType
    """Filter by execution status."""
    flow_name: _builtins.str
    """Filter by flow name (not flow_id)."""
    root_run_id: _builtins.str
    """Filter to runs under this root run (UUID). Includes the root itself."""
    parent_run_id: _builtins.str
    """Filter to direct children of this parent run (UUID)."""
    roots_only: _builtins.bool
    """Filter to only root runs (runs where parent_run_id is None)."""
    max_depth: _builtins.int
    """Maximum depth for hierarchy queries (0 = root only)."""
    limit: _builtins.int
    """Maximum number of results."""
    offset: _builtins.int
    """Number of results to skip."""
    def __init__(
        self,
        *,
        status: _common_pb2.ExecutionStatus.ValueType | None = ...,
        flow_name: _builtins.str | None = ...,
        root_run_id: _builtins.str | None = ...,
        parent_run_id: _builtins.str | None = ...,
        roots_only: _builtins.bool = ...,
        max_depth: _builtins.int | None = ...,
        limit: _builtins.int | None = ...,
        offset: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_flow_name", b"_flow_name", "_limit", b"_limit", "_max_depth", b"_max_depth", "_offset", b"_offset", "_parent_run_id", b"_parent_run_id", "_root_run_id", b"_root_run_id", "_status", b"_status", "flow_name", b"flow_name", "limit", b"limit", "max_depth", b"max_depth", "offset", b"offset", "parent_run_id", b"parent_run_id", "root_run_id", b"root_run_id", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_flow_name", b"_flow_name", "_limit", b"_limit", "_max_depth", b"_max_depth", "_offset", b"_offset", "_parent_run_id", b"_parent_run_id", "_root_run_id", b"_root_run_id", "_status", b"_status", "flow_name", b"flow_name", "limit", b"limit", "max_depth", b"max_depth", "offset", b"offset", "parent_run_id", b"parent_run_id", "root_run_id", b"root_run_id", "roots_only", b"roots_only", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__flow_name: _TypeAlias = _typing.Literal["flow_name"]  # noqa: Y015
    _WhichOneofArgType__flow_name: _TypeAlias = _typing.Literal["_flow_name", b"_flow_name"]  # noqa: Y015
    _WhichOneofReturnType__limit: _TypeAlias = _typing.Literal["limit"]  # noqa: Y015
    _WhichOneofArgType__limit: _TypeAlias = _typing.Literal["_limit", b"_limit"]  # noqa: Y015
    _WhichOneofReturnType__max_depth: _TypeAlias = _typing.Literal["max_depth"]  # noqa: Y015
    _WhichOneofArgType__max_depth: _TypeAlias = _typing.Literal["_max_depth", b"_max_depth"]  # noqa: Y015
    _WhichOneofReturnType__offset: _TypeAlias = _typing.Literal["offset"]  # noqa: Y015
    _WhichOneofArgType__offset: _TypeAlias = _typing.Literal["_offset", b"_offset"]  # noqa: Y015
    _WhichOneofReturnType__parent_run_id: _TypeAlias = _typing.Literal["parent_run_id"]  # noqa: Y015
    _WhichOneofArgType__parent_run_id: _TypeAlias = _typing.Literal["_parent_run_id", b"_parent_run_id"]  # noqa: Y015
    _WhichOneofReturnType__root_run_id: _TypeAlias = _typing.Literal["root_run_id"]  # noqa: Y015
    _WhichOneofArgType__root_run_id: _TypeAlias = _typing.Literal["_root_run_id", b"_root_run_id"]  # noqa: Y015
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__flow_name) -> _WhichOneofReturnType__flow_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__limit) -> _WhichOneofReturnType__limit | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_depth) -> _WhichOneofReturnType__max_depth | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__offset) -> _WhichOneofReturnType__offset | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parent_run_id) -> _WhichOneofReturnType__parent_run_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__root_run_id) -> _WhichOneofReturnType__root_run_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...

Global___ListRunsRequest: _TypeAlias = ListRunsRequest  # noqa: Y015

@_typing.final
class GetRunRequest(_message.Message):
    """--- GetRun ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    WAIT_FIELD_NUMBER: _builtins.int
    TIMEOUT_SECS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    wait: _builtins.bool
    """If true, block until the run completes."""
    timeout_secs: _builtins.int
    """Maximum seconds to wait when wait=true (default 300)."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        wait: _builtins.bool = ...,
        timeout_secs: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_timeout_secs", b"_timeout_secs", "timeout_secs", b"timeout_secs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_timeout_secs", b"_timeout_secs", "run_id", b"run_id", "timeout_secs", b"timeout_secs", "wait", b"wait"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__timeout_secs: _TypeAlias = _typing.Literal["timeout_secs"]  # noqa: Y015
    _WhichOneofArgType__timeout_secs: _TypeAlias = _typing.Literal["_timeout_secs", b"_timeout_secs"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timeout_secs) -> _WhichOneofReturnType__timeout_secs | None: ...

Global___GetRunRequest: _TypeAlias = GetRunRequest  # noqa: Y015

@_typing.final
class GetRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUMMARY_FIELD_NUMBER: _builtins.int
    STEPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def summary(self) -> Global___RunSummary: ...
    @_builtins.property
    def steps(self) -> _containers.RepeatedCompositeFieldContainer[Global___StepStatus]: ...
    def __init__(
        self,
        *,
        summary: Global___RunSummary | None = ...,
        steps: _abc.Iterable[Global___StepStatus] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["steps", b"steps", "summary", b"summary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRunResponse: _TypeAlias = GetRunResponse  # noqa: Y015

@_typing.final
class DeleteRunRequest(_message.Message):
    """--- DeleteRun ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteRunRequest: _TypeAlias = DeleteRunRequest  # noqa: Y015

@_typing.final
class DeleteRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DeleteRunResponse: _TypeAlias = DeleteRunResponse  # noqa: Y015

@_typing.final
class GetRunItemsRequest(_message.Message):
    """--- GetRunItems ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    RESULT_ORDER_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    result_order: _common_pb2.ResultOrder.ValueType
    """Result ordering."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        result_order: _common_pb2.ResultOrder.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result_order", b"result_order", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRunItemsRequest: _TypeAlias = GetRunItemsRequest  # noqa: Y015

@_typing.final
class GetRunItemsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.ItemResult]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[_common_pb2.ItemResult] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRunItemsResponse: _TypeAlias = GetRunItemsResponse  # noqa: Y015

@_typing.final
class GetRunFlowRequest(_message.Message):
    """--- GetRunFlow ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRunFlowRequest: _TypeAlias = GetRunFlowRequest  # noqa: Y015

@_typing.final
class GetRunFlowResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FLOW_FIELD_NUMBER: _builtins.int
    FLOW_ID_FIELD_NUMBER: _builtins.int
    flow_id: _builtins.str
    @_builtins.property
    def flow(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        flow: _struct_pb2.Struct | None = ...,
        flow_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["flow", b"flow"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flow", b"flow", "flow_id", b"flow_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRunFlowResponse: _TypeAlias = GetRunFlowResponse  # noqa: Y015

@_typing.final
class GetRunStepsRequest(_message.Message):
    """--- GetRunSteps ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    ITEM_INDEX_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    item_index: _builtins.int
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        item_index: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_item_index", b"_item_index", "item_index", b"item_index"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_item_index", b"_item_index", "item_index", b"item_index", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__item_index: _TypeAlias = _typing.Literal["item_index"]  # noqa: Y015
    _WhichOneofArgType__item_index: _TypeAlias = _typing.Literal["_item_index", b"_item_index"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__item_index) -> _WhichOneofReturnType__item_index | None: ...

Global___GetRunStepsRequest: _TypeAlias = GetRunStepsRequest  # noqa: Y015

@_typing.final
class GetRunStepsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STEPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def steps(self) -> _containers.RepeatedCompositeFieldContainer[Global___StepStatus]: ...
    def __init__(
        self,
        *,
        steps: _abc.Iterable[Global___StepStatus] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["steps", b"steps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRunStepsResponse: _TypeAlias = GetRunStepsResponse  # noqa: Y015

@_typing.final
class GetStepDetailRequest(_message.Message):
    """--- GetStepDetail ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    STEP_ID_FIELD_NUMBER: _builtins.int
    ITEM_INDEX_FIELD_NUMBER: _builtins.int
    ASOF_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    step_id: _builtins.str
    item_index: _builtins.int
    asof: _builtins.int
    """Read-after-write consistency: only return data if the store has
    processed at least this journal sequence number.
    """
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        step_id: _builtins.str = ...,
        item_index: _builtins.int | None = ...,
        asof: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_asof", b"_asof", "_item_index", b"_item_index", "asof", b"asof", "item_index", b"item_index"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_asof", b"_asof", "_item_index", b"_item_index", "asof", b"asof", "item_index", b"item_index", "run_id", b"run_id", "step_id", b"step_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__asof: _TypeAlias = _typing.Literal["asof"]  # noqa: Y015
    _WhichOneofArgType__asof: _TypeAlias = _typing.Literal["_asof", b"_asof"]  # noqa: Y015
    _WhichOneofReturnType__item_index: _TypeAlias = _typing.Literal["item_index"]  # noqa: Y015
    _WhichOneofArgType__item_index: _TypeAlias = _typing.Literal["_item_index", b"_item_index"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__asof) -> _WhichOneofReturnType__asof | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__item_index) -> _WhichOneofReturnType__item_index | None: ...

Global___GetStepDetailRequest: _TypeAlias = GetStepDetailRequest  # noqa: Y015

@_typing.final
class GetStepDetailResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STEP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def step(self) -> Global___StepStatus: ...
    def __init__(
        self,
        *,
        step: Global___StepStatus | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["step", b"step"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["step", b"step"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetStepDetailResponse: _TypeAlias = GetStepDetailResponse  # noqa: Y015

@_typing.final
class GetRunEventsRequest(_message.Message):
    """--- GetRunEvents (server-streaming → SSE) ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    SINCE_FIELD_NUMBER: _builtins.int
    EVENT_TYPES_FIELD_NUMBER: _builtins.int
    INCLUDE_SUB_RUNS_FIELD_NUMBER: _builtins.int
    INCLUDE_RESULTS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    since: _builtins.int
    """Resume from this sequence number (for SSE Last-Event-ID)."""
    event_types: _builtins.str
    """Filter by event types (comma-separated)."""
    include_sub_runs: _builtins.bool
    """Include events from sub-runs."""
    include_results: _builtins.bool
    """Include step/run results in events."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        since: _builtins.int | None = ...,
        event_types: _builtins.str | None = ...,
        include_sub_runs: _builtins.bool = ...,
        include_results: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_event_types", b"_event_types", "_since", b"_since", "event_types", b"event_types", "since", b"since"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_event_types", b"_event_types", "_since", b"_since", "event_types", b"event_types", "include_results", b"include_results", "include_sub_runs", b"include_sub_runs", "run_id", b"run_id", "since", b"since"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__event_types: _TypeAlias = _typing.Literal["event_types"]  # noqa: Y015
    _WhichOneofArgType__event_types: _TypeAlias = _typing.Literal["_event_types", b"_event_types"]  # noqa: Y015
    _WhichOneofReturnType__since: _TypeAlias = _typing.Literal["since"]  # noqa: Y015
    _WhichOneofArgType__since: _TypeAlias = _typing.Literal["_since", b"_since"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__event_types) -> _WhichOneofReturnType__event_types | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__since) -> _WhichOneofReturnType__since | None: ...

Global___GetRunEventsRequest: _TypeAlias = GetRunEventsRequest  # noqa: Y015

@_typing.final
class CancelRunRequest(_message.Message):
    """--- CancelRun ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CancelRunRequest: _TypeAlias = CancelRunRequest  # noqa: Y015

@_typing.final
class CancelRunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUMMARY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def summary(self) -> Global___RunSummary: ...
    def __init__(
        self,
        *,
        summary: Global___RunSummary | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CancelRunResponse: _TypeAlias = CancelRunResponse  # noqa: Y015

@_typing.final
class ListRunsResponse(_message.Message):
    """--- ListRuns response ---"""

    DESCRIPTOR: _descriptor.Descriptor

    RUNS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___RunSummary]: ...
    def __init__(
        self,
        *,
        runs: _abc.Iterable[Global___RunSummary] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["runs", b"runs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListRunsResponse: _TypeAlias = ListRunsResponse  # noqa: Y015

@_typing.final
class RunSummary(_message.Message):
    """=============================================================================
    Shared types
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    FLOW_ID_FIELD_NUMBER: _builtins.int
    FLOW_NAME_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    COMPLETED_AT_FIELD_NUMBER: _builtins.int
    ROOT_RUN_ID_FIELD_NUMBER: _builtins.int
    PARENT_RUN_ID_FIELD_NUMBER: _builtins.int
    ORCHESTRATOR_ID_FIELD_NUMBER: _builtins.int
    CREATED_AT_SEQNO_FIELD_NUMBER: _builtins.int
    FINISHED_AT_SEQNO_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    flow_id: _builtins.str
    flow_name: _builtins.str
    status: _common_pb2.ExecutionStatus.ValueType
    root_run_id: _builtins.str
    """Run hierarchy fields.
    Root run ID (UUID). For top-level runs, equals run_id.
    """
    parent_run_id: _builtins.str
    """Parent run ID (UUID). Present only for sub-flow runs."""
    orchestrator_id: _builtins.str
    """The orchestrator currently managing this run."""
    created_at_seqno: _builtins.int
    """Journal sequence numbers for recovery and consistency."""
    finished_at_seqno: _builtins.int
    @_builtins.property
    def items(self) -> _common_pb2.ItemStatistics: ...
    @_builtins.property
    def created_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def completed_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        flow_id: _builtins.str = ...,
        flow_name: _builtins.str | None = ...,
        status: _common_pb2.ExecutionStatus.ValueType = ...,
        items: _common_pb2.ItemStatistics | None = ...,
        created_at: _timestamp_pb2.Timestamp | None = ...,
        completed_at: _timestamp_pb2.Timestamp | None = ...,
        root_run_id: _builtins.str = ...,
        parent_run_id: _builtins.str | None = ...,
        orchestrator_id: _builtins.str | None = ...,
        created_at_seqno: _builtins.int = ...,
        finished_at_seqno: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at", "_finished_at_seqno", b"_finished_at_seqno", "_flow_name", b"_flow_name", "_orchestrator_id", b"_orchestrator_id", "_parent_run_id", b"_parent_run_id", "completed_at", b"completed_at", "created_at", b"created_at", "finished_at_seqno", b"finished_at_seqno", "flow_name", b"flow_name", "items", b"items", "orchestrator_id", b"orchestrator_id", "parent_run_id", b"parent_run_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at", "_finished_at_seqno", b"_finished_at_seqno", "_flow_name", b"_flow_name", "_orchestrator_id", b"_orchestrator_id", "_parent_run_id", b"_parent_run_id", "completed_at", b"completed_at", "created_at", b"created_at", "created_at_seqno", b"created_at_seqno", "finished_at_seqno", b"finished_at_seqno", "flow_id", b"flow_id", "flow_name", b"flow_name", "items", b"items", "orchestrator_id", b"orchestrator_id", "parent_run_id", b"parent_run_id", "root_run_id", b"root_run_id", "run_id", b"run_id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__completed_at: _TypeAlias = _typing.Literal["completed_at"]  # noqa: Y015
    _WhichOneofArgType__completed_at: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at"]  # noqa: Y015
    _WhichOneofReturnType__finished_at_seqno: _TypeAlias = _typing.Literal["finished_at_seqno"]  # noqa: Y015
    _WhichOneofArgType__finished_at_seqno: _TypeAlias = _typing.Literal["_finished_at_seqno", b"_finished_at_seqno"]  # noqa: Y015
    _WhichOneofReturnType__flow_name: _TypeAlias = _typing.Literal["flow_name"]  # noqa: Y015
    _WhichOneofArgType__flow_name: _TypeAlias = _typing.Literal["_flow_name", b"_flow_name"]  # noqa: Y015
    _WhichOneofReturnType__orchestrator_id: _TypeAlias = _typing.Literal["orchestrator_id"]  # noqa: Y015
    _WhichOneofArgType__orchestrator_id: _TypeAlias = _typing.Literal["_orchestrator_id", b"_orchestrator_id"]  # noqa: Y015
    _WhichOneofReturnType__parent_run_id: _TypeAlias = _typing.Literal["parent_run_id"]  # noqa: Y015
    _WhichOneofArgType__parent_run_id: _TypeAlias = _typing.Literal["_parent_run_id", b"_parent_run_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__completed_at) -> _WhichOneofReturnType__completed_at | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__finished_at_seqno) -> _WhichOneofReturnType__finished_at_seqno | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__flow_name) -> _WhichOneofReturnType__flow_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__orchestrator_id) -> _WhichOneofReturnType__orchestrator_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parent_run_id) -> _WhichOneofReturnType__parent_run_id | None: ...

Global___RunSummary: _TypeAlias = RunSummary  # noqa: Y015

@_typing.final
class StepStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STEP_ID_FIELD_NUMBER: _builtins.int
    STEP_INDEX_FIELD_NUMBER: _builtins.int
    ITEM_INDEX_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    COMPONENT_FIELD_NUMBER: _builtins.int
    OUTPUT_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    ERROR_CODE_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    COMPLETED_AT_FIELD_NUMBER: _builtins.int
    JOURNAL_SEQNO_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    step_id: _builtins.str
    step_index: _builtins.int
    item_index: _builtins.int
    """Item index (0-based). Required for batch runs."""
    status: _common_pb2.ExecutionStatus.ValueType
    component: _builtins.str
    error_message: _builtins.str
    error_code: _builtins.int
    journal_seqno: _builtins.int
    """Journal sequence number of the event that produced this status."""
    @_builtins.property
    def output(self) -> _struct_pb2.Value:
        """Step result (present when completed or failed)."""

    @_builtins.property
    def started_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def completed_at(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def updated_at(self) -> _timestamp_pb2.Timestamp:
        """When this status was last updated."""

    def __init__(
        self,
        *,
        step_id: _builtins.str = ...,
        step_index: _builtins.int = ...,
        item_index: _builtins.int = ...,
        status: _common_pb2.ExecutionStatus.ValueType = ...,
        component: _builtins.str | None = ...,
        output: _struct_pb2.Value | None = ...,
        error_message: _builtins.str | None = ...,
        error_code: _builtins.int | None = ...,
        started_at: _timestamp_pb2.Timestamp | None = ...,
        completed_at: _timestamp_pb2.Timestamp | None = ...,
        journal_seqno: _builtins.int = ...,
        updated_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at", "_component", b"_component", "_error_code", b"_error_code", "_error_message", b"_error_message", "_output", b"_output", "_started_at", b"_started_at", "_updated_at", b"_updated_at", "completed_at", b"completed_at", "component", b"component", "error_code", b"error_code", "error_message", b"error_message", "output", b"output", "started_at", b"started_at", "updated_at", b"updated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at", "_component", b"_component", "_error_code", b"_error_code", "_error_message", b"_error_message", "_output", b"_output", "_started_at", b"_started_at", "_updated_at", b"_updated_at", "completed_at", b"completed_at", "component", b"component", "error_code", b"error_code", "error_message", b"error_message", "item_index", b"item_index", "journal_seqno", b"journal_seqno", "output", b"output", "started_at", b"started_at", "status", b"status", "step_id", b"step_id", "step_index", b"step_index", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__completed_at: _TypeAlias = _typing.Literal["completed_at"]  # noqa: Y015
    _WhichOneofArgType__completed_at: _TypeAlias = _typing.Literal["_completed_at", b"_completed_at"]  # noqa: Y015
    _WhichOneofReturnType__component: _TypeAlias = _typing.Literal["component"]  # noqa: Y015
    _WhichOneofArgType__component: _TypeAlias = _typing.Literal["_component", b"_component"]  # noqa: Y015
    _WhichOneofReturnType__error_code: _TypeAlias = _typing.Literal["error_code"]  # noqa: Y015
    _WhichOneofArgType__error_code: _TypeAlias = _typing.Literal["_error_code", b"_error_code"]  # noqa: Y015
    _WhichOneofReturnType__error_message: _TypeAlias = _typing.Literal["error_message"]  # noqa: Y015
    _WhichOneofArgType__error_message: _TypeAlias = _typing.Literal["_error_message", b"_error_message"]  # noqa: Y015
    _WhichOneofReturnType__output: _TypeAlias = _typing.Literal["output"]  # noqa: Y015
    _WhichOneofArgType__output: _TypeAlias = _typing.Literal["_output", b"_output"]  # noqa: Y015
    _WhichOneofReturnType__started_at: _TypeAlias = _typing.Literal["started_at"]  # noqa: Y015
    _WhichOneofArgType__started_at: _TypeAlias = _typing.Literal["_started_at", b"_started_at"]  # noqa: Y015
    _WhichOneofReturnType__updated_at: _TypeAlias = _typing.Literal["updated_at"]  # noqa: Y015
    _WhichOneofArgType__updated_at: _TypeAlias = _typing.Literal["_updated_at", b"_updated_at"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__completed_at) -> _WhichOneofReturnType__completed_at | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__component) -> _WhichOneofReturnType__component | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__error_code) -> _WhichOneofReturnType__error_code | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__error_message) -> _WhichOneofReturnType__error_message | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__output) -> _WhichOneofReturnType__output | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__started_at) -> _WhichOneofReturnType__started_at | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__updated_at) -> _WhichOneofReturnType__updated_at | None: ...

Global___StepStatus: _TypeAlias = StepStatus  # noqa: Y015

@_typing.final
class StatusEvent(_message.Message):
    """=============================================================================
    Status Events (strongly typed)
    =============================================================================

    A status event from the execution journal.

    Sent as SSE events with:
    - id = sequence_number
    - event = the event type name (e.g., "step_started")
    - data = JSON-serialized StatusEvent
    """

    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_NUMBER_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    RUN_CREATED_FIELD_NUMBER: _builtins.int
    STEP_STARTED_FIELD_NUMBER: _builtins.int
    STEP_COMPLETED_FIELD_NUMBER: _builtins.int
    STEP_READY_FIELD_NUMBER: _builtins.int
    ITEM_COMPLETED_FIELD_NUMBER: _builtins.int
    RUN_COMPLETED_FIELD_NUMBER: _builtins.int
    SUB_RUN_CREATED_FIELD_NUMBER: _builtins.int
    STEPS_NEEDED_FIELD_NUMBER: _builtins.int
    sequence_number: _builtins.int
    """Journal sequence number (used as SSE id)."""
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp:
        """Timestamp when this event was recorded."""

    @_builtins.property
    def run_created(self) -> Global___RunCreatedEvent: ...
    @_builtins.property
    def step_started(self) -> Global___StepStartedEvent: ...
    @_builtins.property
    def step_completed(self) -> Global___StepCompletedEvent: ...
    @_builtins.property
    def step_ready(self) -> Global___StepReadyEvent: ...
    @_builtins.property
    def item_completed(self) -> Global___ItemCompletedEvent: ...
    @_builtins.property
    def run_completed(self) -> Global___RunCompletedEvent: ...
    @_builtins.property
    def sub_run_created(self) -> Global___SubRunCreatedEvent: ...
    @_builtins.property
    def steps_needed(self) -> Global___StepsNeededEvent: ...
    def __init__(
        self,
        *,
        sequence_number: _builtins.int = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        run_created: Global___RunCreatedEvent | None = ...,
        step_started: Global___StepStartedEvent | None = ...,
        step_completed: Global___StepCompletedEvent | None = ...,
        step_ready: Global___StepReadyEvent | None = ...,
        item_completed: Global___ItemCompletedEvent | None = ...,
        run_completed: Global___RunCompletedEvent | None = ...,
        sub_run_created: Global___SubRunCreatedEvent | None = ...,
        steps_needed: Global___StepsNeededEvent | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "item_completed", b"item_completed", "run_completed", b"run_completed", "run_created", b"run_created", "step_completed", b"step_completed", "step_ready", b"step_ready", "step_started", b"step_started", "steps_needed", b"steps_needed", "sub_run_created", b"sub_run_created", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "item_completed", b"item_completed", "run_completed", b"run_completed", "run_created", b"run_created", "sequence_number", b"sequence_number", "step_completed", b"step_completed", "step_ready", b"step_ready", "step_started", b"step_started", "steps_needed", b"steps_needed", "sub_run_created", b"sub_run_created", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["run_created", "step_started", "step_completed", "step_ready", "item_completed", "run_completed", "sub_run_created", "steps_needed"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___StatusEvent: _TypeAlias = StatusEvent  # noqa: Y015

@_typing.final
class RunCreatedEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    FLOW_ID_FIELD_NUMBER: _builtins.int
    ITEM_COUNT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    flow_id: _builtins.str
    item_count: _builtins.int
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        flow_id: _builtins.str = ...,
        item_count: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flow_id", b"flow_id", "item_count", b"item_count", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RunCreatedEvent: _TypeAlias = RunCreatedEvent  # noqa: Y015

@_typing.final
class StepStartedEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    ITEM_INDEX_FIELD_NUMBER: _builtins.int
    STEP_INDEX_FIELD_NUMBER: _builtins.int
    STEP_ID_FIELD_NUMBER: _builtins.int
    ATTEMPT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    item_index: _builtins.int
    step_index: _builtins.int
    step_id: _builtins.str
    attempt: _builtins.int
    """Execution attempt number (1-based, >1 for retries)."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        item_index: _builtins.int = ...,
        step_index: _builtins.int = ...,
        step_id: _builtins.str | None = ...,
        attempt: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_step_id", b"_step_id", "step_id", b"step_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_step_id", b"_step_id", "attempt", b"attempt", "item_index", b"item_index", "run_id", b"run_id", "step_id", b"step_id", "step_index", b"step_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__step_id: _TypeAlias = _typing.Literal["step_id"]  # noqa: Y015
    _WhichOneofArgType__step_id: _TypeAlias = _typing.Literal["_step_id", b"_step_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__step_id) -> _WhichOneofReturnType__step_id | None: ...

Global___StepStartedEvent: _TypeAlias = StepStartedEvent  # noqa: Y015

@_typing.final
class StepCompletedEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    ITEM_INDEX_FIELD_NUMBER: _builtins.int
    STEP_INDEX_FIELD_NUMBER: _builtins.int
    STEP_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    item_index: _builtins.int
    step_index: _builtins.int
    step_id: _builtins.str
    status: _common_pb2.ExecutionStatus.ValueType
    """Whether the step succeeded or failed."""
    @_builtins.property
    def result(self) -> _struct_pb2.Value:
        """The step result. Only included when include_results=true."""

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        item_index: _builtins.int = ...,
        step_index: _builtins.int = ...,
        step_id: _builtins.str | None = ...,
        status: _common_pb2.ExecutionStatus.ValueType = ...,
        result: _struct_pb2.Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_result", b"_result", "_step_id", b"_step_id", "result", b"result", "step_id", b"step_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_result", b"_result", "_step_id", b"_step_id", "item_index", b"item_index", "result", b"result", "run_id", b"run_id", "status", b"status", "step_id", b"step_id", "step_index", b"step_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__result: _TypeAlias = _typing.Literal["result"]  # noqa: Y015
    _WhichOneofArgType__result: _TypeAlias = _typing.Literal["_result", b"_result"]  # noqa: Y015
    _WhichOneofReturnType__step_id: _TypeAlias = _typing.Literal["step_id"]  # noqa: Y015
    _WhichOneofArgType__step_id: _TypeAlias = _typing.Literal["_step_id", b"_step_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__result) -> _WhichOneofReturnType__result | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__step_id) -> _WhichOneofReturnType__step_id | None: ...

Global___StepCompletedEvent: _TypeAlias = StepCompletedEvent  # noqa: Y015

@_typing.final
class StepReadyEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    ITEM_INDEX_FIELD_NUMBER: _builtins.int
    STEP_INDEX_FIELD_NUMBER: _builtins.int
    STEP_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    item_index: _builtins.int
    step_index: _builtins.int
    step_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        item_index: _builtins.int = ...,
        step_index: _builtins.int = ...,
        step_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_step_id", b"_step_id", "step_id", b"step_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_step_id", b"_step_id", "item_index", b"item_index", "run_id", b"run_id", "step_id", b"step_id", "step_index", b"step_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__step_id: _TypeAlias = _typing.Literal["step_id"]  # noqa: Y015
    _WhichOneofArgType__step_id: _TypeAlias = _typing.Literal["_step_id", b"_step_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__step_id) -> _WhichOneofReturnType__step_id | None: ...

Global___StepReadyEvent: _TypeAlias = StepReadyEvent  # noqa: Y015

@_typing.final
class ItemCompletedEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    ITEM_INDEX_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    item_index: _builtins.int
    @_builtins.property
    def result(self) -> _struct_pb2.Value:
        """The item result. Only included when include_results=true."""

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        item_index: _builtins.int = ...,
        result: _struct_pb2.Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_result", b"_result", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_result", b"_result", "item_index", b"item_index", "result", b"result", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__result: _TypeAlias = _typing.Literal["result"]  # noqa: Y015
    _WhichOneofArgType__result: _TypeAlias = _typing.Literal["_result", b"_result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__result) -> _WhichOneofReturnType__result | None: ...

Global___ItemCompletedEvent: _TypeAlias = ItemCompletedEvent  # noqa: Y015

@_typing.final
class RunCompletedEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    status: _common_pb2.ExecutionStatus.ValueType
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        status: _common_pb2.ExecutionStatus.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RunCompletedEvent: _TypeAlias = RunCompletedEvent  # noqa: Y015

@_typing.final
class SubRunCreatedEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    PARENT_RUN_ID_FIELD_NUMBER: _builtins.int
    FLOW_ID_FIELD_NUMBER: _builtins.int
    ITEM_COUNT_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """The sub-run's ID (UUID)."""
    parent_run_id: _builtins.str
    """Parent run ID (UUID) that spawned this sub-run."""
    flow_id: _builtins.str
    """The flow being executed by the sub-run."""
    item_count: _builtins.int
    """Number of items in the sub-run."""
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        parent_run_id: _builtins.str = ...,
        flow_id: _builtins.str = ...,
        item_count: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flow_id", b"flow_id", "item_count", b"item_count", "parent_run_id", b"parent_run_id", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubRunCreatedEvent: _TypeAlias = SubRunCreatedEvent  # noqa: Y015

@_typing.final
class StepsNeededEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    ITEM_INDEX_FIELD_NUMBER: _builtins.int
    STEP_IDS_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID (UUID)."""
    item_index: _builtins.int
    """Item index (0-based)."""
    @_builtins.property
    def step_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Step IDs that need to execute for this item.
        Emitted after flow analysis and whenever conditional branches change the
        needed step set.
        """

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        item_index: _builtins.int = ...,
        step_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["item_index", b"item_index", "run_id", b"run_id", "step_ids", b"step_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StepsNeededEvent: _TypeAlias = StepsNeededEvent  # noqa: Y015
