"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

import abc
import collections.abc
import grpc
import grpc.aio
from . import runs_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_RunsServiceCreateRunType = typing_extensions.TypeVar(
    '_RunsServiceCreateRunType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.CreateRunRequest,
        runs_pb2.CreateRunResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.CreateRunRequest,
        runs_pb2.CreateRunResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.CreateRunRequest,
        runs_pb2.CreateRunResponse,
    ],
)

_RunsServiceListRunsType = typing_extensions.TypeVar(
    '_RunsServiceListRunsType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.ListRunsRequest,
        runs_pb2.ListRunsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.ListRunsRequest,
        runs_pb2.ListRunsResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.ListRunsRequest,
        runs_pb2.ListRunsResponse,
    ],
)

_RunsServiceGetRunType = typing_extensions.TypeVar(
    '_RunsServiceGetRunType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetRunRequest,
        runs_pb2.GetRunResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetRunRequest,
        runs_pb2.GetRunResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetRunRequest,
        runs_pb2.GetRunResponse,
    ],
)

_RunsServiceDeleteRunType = typing_extensions.TypeVar(
    '_RunsServiceDeleteRunType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.DeleteRunRequest,
        runs_pb2.DeleteRunResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.DeleteRunRequest,
        runs_pb2.DeleteRunResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.DeleteRunRequest,
        runs_pb2.DeleteRunResponse,
    ],
)

_RunsServiceGetRunItemsType = typing_extensions.TypeVar(
    '_RunsServiceGetRunItemsType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetRunItemsRequest,
        runs_pb2.GetRunItemsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetRunItemsRequest,
        runs_pb2.GetRunItemsResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetRunItemsRequest,
        runs_pb2.GetRunItemsResponse,
    ],
)

_RunsServiceGetRunFlowType = typing_extensions.TypeVar(
    '_RunsServiceGetRunFlowType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetRunFlowRequest,
        runs_pb2.GetRunFlowResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetRunFlowRequest,
        runs_pb2.GetRunFlowResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetRunFlowRequest,
        runs_pb2.GetRunFlowResponse,
    ],
)

_RunsServiceGetRunStepsType = typing_extensions.TypeVar(
    '_RunsServiceGetRunStepsType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetRunStepsRequest,
        runs_pb2.GetRunStepsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetRunStepsRequest,
        runs_pb2.GetRunStepsResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetRunStepsRequest,
        runs_pb2.GetRunStepsResponse,
    ],
)

_RunsServiceGetStepDetailType = typing_extensions.TypeVar(
    '_RunsServiceGetStepDetailType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetStepDetailRequest,
        runs_pb2.GetStepDetailResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetStepDetailRequest,
        runs_pb2.GetStepDetailResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.GetStepDetailRequest,
        runs_pb2.GetStepDetailResponse,
    ],
)

_RunsServiceGetRunEventsType = typing_extensions.TypeVar(
    '_RunsServiceGetRunEventsType',
    grpc.UnaryStreamMultiCallable[
        runs_pb2.GetRunEventsRequest,
        runs_pb2.StatusEvent,
    ],
    grpc.aio.UnaryStreamMultiCallable[
        runs_pb2.GetRunEventsRequest,
        runs_pb2.StatusEvent,
    ],
    default=grpc.UnaryStreamMultiCallable[
        runs_pb2.GetRunEventsRequest,
        runs_pb2.StatusEvent,
    ],
)

_RunsServiceCancelRunType = typing_extensions.TypeVar(
    '_RunsServiceCancelRunType',
    grpc.UnaryUnaryMultiCallable[
        runs_pb2.CancelRunRequest,
        runs_pb2.CancelRunResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.CancelRunRequest,
        runs_pb2.CancelRunResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        runs_pb2.CancelRunRequest,
        runs_pb2.CancelRunResponse,
    ],
)

class RunsServiceStub(typing.Generic[_RunsServiceCreateRunType, _RunsServiceListRunsType, _RunsServiceGetRunType, _RunsServiceDeleteRunType, _RunsServiceGetRunItemsType, _RunsServiceGetRunFlowType, _RunsServiceGetRunStepsType, _RunsServiceGetStepDetailType, _RunsServiceGetRunEventsType, _RunsServiceCancelRunType]):
    """Service for managing workflow runs."""

    @typing.overload
    def __init__(self: RunsServiceStub[
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.CreateRunRequest,
            runs_pb2.CreateRunResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.ListRunsRequest,
            runs_pb2.ListRunsResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.GetRunRequest,
            runs_pb2.GetRunResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.DeleteRunRequest,
            runs_pb2.DeleteRunResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.GetRunItemsRequest,
            runs_pb2.GetRunItemsResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.GetRunFlowRequest,
            runs_pb2.GetRunFlowResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.GetRunStepsRequest,
            runs_pb2.GetRunStepsResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.GetStepDetailRequest,
            runs_pb2.GetStepDetailResponse,
        ],
        grpc.UnaryStreamMultiCallable[
            runs_pb2.GetRunEventsRequest,
            runs_pb2.StatusEvent,
        ],
        grpc.UnaryUnaryMultiCallable[
            runs_pb2.CancelRunRequest,
            runs_pb2.CancelRunResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: RunsServiceStub[
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.CreateRunRequest,
            runs_pb2.CreateRunResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.ListRunsRequest,
            runs_pb2.ListRunsResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.GetRunRequest,
            runs_pb2.GetRunResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.DeleteRunRequest,
            runs_pb2.DeleteRunResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.GetRunItemsRequest,
            runs_pb2.GetRunItemsResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.GetRunFlowRequest,
            runs_pb2.GetRunFlowResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.GetRunStepsRequest,
            runs_pb2.GetRunStepsResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.GetStepDetailRequest,
            runs_pb2.GetStepDetailResponse,
        ],
        grpc.aio.UnaryStreamMultiCallable[
            runs_pb2.GetRunEventsRequest,
            runs_pb2.StatusEvent,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            runs_pb2.CancelRunRequest,
            runs_pb2.CancelRunResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    CreateRun: _RunsServiceCreateRunType
    """Create a new run for a flow."""

    ListRuns: _RunsServiceListRunsType
    """List runs with optional filtering."""

    GetRun: _RunsServiceGetRunType
    """Get details of a specific run."""

    DeleteRun: _RunsServiceDeleteRunType
    """Delete a run."""

    GetRunItems: _RunsServiceGetRunItemsType
    """Get item results for a run."""

    GetRunFlow: _RunsServiceGetRunFlowType
    """Get the flow definition associated with a run."""

    GetRunSteps: _RunsServiceGetRunStepsType
    """Get step statuses for a run."""

    GetStepDetail: _RunsServiceGetStepDetailType
    """Get detailed status for a specific step."""

    GetRunEvents: _RunsServiceGetRunEventsType
    """Stream status events for a run (SSE via tonic-rest)."""

    CancelRun: _RunsServiceCancelRunType
    """Cancel a running run."""

RunsServiceAsyncStub: typing_extensions.TypeAlias = RunsServiceStub[
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.CreateRunRequest,
        runs_pb2.CreateRunResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.ListRunsRequest,
        runs_pb2.ListRunsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetRunRequest,
        runs_pb2.GetRunResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.DeleteRunRequest,
        runs_pb2.DeleteRunResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetRunItemsRequest,
        runs_pb2.GetRunItemsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetRunFlowRequest,
        runs_pb2.GetRunFlowResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetRunStepsRequest,
        runs_pb2.GetRunStepsResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.GetStepDetailRequest,
        runs_pb2.GetStepDetailResponse,
    ],
    grpc.aio.UnaryStreamMultiCallable[
        runs_pb2.GetRunEventsRequest,
        runs_pb2.StatusEvent,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        runs_pb2.CancelRunRequest,
        runs_pb2.CancelRunResponse,
    ],
]

class RunsServiceServicer(metaclass=abc.ABCMeta):
    """Service for managing workflow runs."""

    @abc.abstractmethod
    def CreateRun(
        self,
        request: runs_pb2.CreateRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.CreateRunResponse, collections.abc.Awaitable[runs_pb2.CreateRunResponse]]:
        """Create a new run for a flow."""

    @abc.abstractmethod
    def ListRuns(
        self,
        request: runs_pb2.ListRunsRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.ListRunsResponse, collections.abc.Awaitable[runs_pb2.ListRunsResponse]]:
        """List runs with optional filtering."""

    @abc.abstractmethod
    def GetRun(
        self,
        request: runs_pb2.GetRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.GetRunResponse, collections.abc.Awaitable[runs_pb2.GetRunResponse]]:
        """Get details of a specific run."""

    @abc.abstractmethod
    def DeleteRun(
        self,
        request: runs_pb2.DeleteRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.DeleteRunResponse, collections.abc.Awaitable[runs_pb2.DeleteRunResponse]]:
        """Delete a run."""

    @abc.abstractmethod
    def GetRunItems(
        self,
        request: runs_pb2.GetRunItemsRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.GetRunItemsResponse, collections.abc.Awaitable[runs_pb2.GetRunItemsResponse]]:
        """Get item results for a run."""

    @abc.abstractmethod
    def GetRunFlow(
        self,
        request: runs_pb2.GetRunFlowRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.GetRunFlowResponse, collections.abc.Awaitable[runs_pb2.GetRunFlowResponse]]:
        """Get the flow definition associated with a run."""

    @abc.abstractmethod
    def GetRunSteps(
        self,
        request: runs_pb2.GetRunStepsRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.GetRunStepsResponse, collections.abc.Awaitable[runs_pb2.GetRunStepsResponse]]:
        """Get step statuses for a run."""

    @abc.abstractmethod
    def GetStepDetail(
        self,
        request: runs_pb2.GetStepDetailRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.GetStepDetailResponse, collections.abc.Awaitable[runs_pb2.GetStepDetailResponse]]:
        """Get detailed status for a specific step."""

    @abc.abstractmethod
    def GetRunEvents(
        self,
        request: runs_pb2.GetRunEventsRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[runs_pb2.StatusEvent], collections.abc.AsyncIterator[runs_pb2.StatusEvent]]:
        """Stream status events for a run (SSE via tonic-rest)."""

    @abc.abstractmethod
    def CancelRun(
        self,
        request: runs_pb2.CancelRunRequest,
        context: _ServicerContext,
    ) -> typing.Union[runs_pb2.CancelRunResponse, collections.abc.Awaitable[runs_pb2.CancelRunResponse]]:
        """Cancel a running run."""

def add_RunsServiceServicer_to_server(servicer: RunsServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
