"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 DataStax Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
"""

from collections import abc as _abc
from grpc import aio as _aio
from . import tasks_pb2 as _tasks_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class TasksServiceStub:
    """Orchestrator-hosted service that workers connect to for receiving tasks.

    This service runs on the orchestrator (or any stateless dispatcher with
    access to the task queue). Workers are *clients* of this service — they
    call PullTasks to receive work.

    Static worker configuration (blob service URL, blobification threshold,
    etc.) is provided via environment variables at deployment time. Only
    per-task information (e.g., the run-owning orchestrator URL) is sent
    in-band via TaskContext.

    Workers report task completion via OrchestratorService.CompleteTask,
    which must reach the orchestrator that owns the specific run (URL
    provided per-task in TaskContext).

    gRPC only — not exposed as REST.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> TasksServiceAsyncStub: ...
    PullTasks: _grpc.UnaryStreamMultiCallable[_tasks_pb2.PullTasksRequest, _tasks_pb2.TaskAssignment]
    """Pull task assignments for a specific plugin.

    The worker specifies which plugin entry it is pulling for (by name from
    the orchestrator's config). The orchestrator validates that the plugin
    uses a compatible transport (e.g., "pull"). If the plugin uses a
    queue-based transport (e.g., NATS, Kafka), this RPC returns FAILED_PRECONDITION.

    The worker also declares its capabilities (concurrency, components).
    The stream stays open for the worker's lifetime — tasks are sent as
    they become available.
    """

@_typing.type_check_only
class TasksServiceAsyncStub(TasksServiceStub):
    """Orchestrator-hosted service that workers connect to for receiving tasks.

    This service runs on the orchestrator (or any stateless dispatcher with
    access to the task queue). Workers are *clients* of this service — they
    call PullTasks to receive work.

    Static worker configuration (blob service URL, blobification threshold,
    etc.) is provided via environment variables at deployment time. Only
    per-task information (e.g., the run-owning orchestrator URL) is sent
    in-band via TaskContext.

    Workers report task completion via OrchestratorService.CompleteTask,
    which must reach the orchestrator that owns the specific run (URL
    provided per-task in TaskContext).

    gRPC only — not exposed as REST.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    PullTasks: _aio.UnaryStreamMultiCallable[_tasks_pb2.PullTasksRequest, _tasks_pb2.TaskAssignment]  # type: ignore[assignment]
    """Pull task assignments for a specific plugin.

    The worker specifies which plugin entry it is pulling for (by name from
    the orchestrator's config). The orchestrator validates that the plugin
    uses a compatible transport (e.g., "pull"). If the plugin uses a
    queue-based transport (e.g., NATS, Kafka), this RPC returns FAILED_PRECONDITION.

    The worker also declares its capabilities (concurrency, components).
    The stream stays open for the worker's lifetime — tasks are sent as
    they become available.
    """

class TasksServiceServicer(metaclass=_abc_1.ABCMeta):
    """Orchestrator-hosted service that workers connect to for receiving tasks.

    This service runs on the orchestrator (or any stateless dispatcher with
    access to the task queue). Workers are *clients* of this service — they
    call PullTasks to receive work.

    Static worker configuration (blob service URL, blobification threshold,
    etc.) is provided via environment variables at deployment time. Only
    per-task information (e.g., the run-owning orchestrator URL) is sent
    in-band via TaskContext.

    Workers report task completion via OrchestratorService.CompleteTask,
    which must reach the orchestrator that owns the specific run (URL
    provided per-task in TaskContext).

    gRPC only — not exposed as REST.
    """

    @_abc_1.abstractmethod
    def PullTasks(
        self,
        request: _tasks_pb2.PullTasksRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_tasks_pb2.TaskAssignment], _abc.AsyncIterator[_tasks_pb2.TaskAssignment]]:
        """Pull task assignments for a specific plugin.

        The worker specifies which plugin entry it is pulling for (by name from
        the orchestrator's config). The orchestrator validates that the plugin
        uses a compatible transport (e.g., "pull"). If the plugin uses a
        queue-based transport (e.g., NATS, Kafka), this RPC returns FAILED_PRECONDITION.

        The worker also declares its capabilities (concurrency, components).
        The stream stays open for the worker's lifetime — tasks are sent as
        they become available.
        """

def add_TasksServiceServicer_to_server(servicer: TasksServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
