# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stepflow/v1/vsock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stepflow/v1/vsock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tasks_pb2 as stepflow_dot_v1_dot_tasks__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17stepflow/v1/vsock.proto\x12\x0bstepflow.v1\x1a\x17stepflow/v1/tasks.proto\"\x80\x01\n\x11VsockTaskEnvelope\x12/\n\nassignment\x18\x01 \x01(\x0b\x32\x1b.stepflow.v1.TaskAssignment\x12\x10\n\x08\x62lob_url\x18\x02 \x01(\t\x12\x11\n\ttasks_url\x18\x03 \x01(\t\x12\x15\n\rotel_endpoint\x18\x04 \x01(\tB;Z9github.com/datastax/stepflow/proto/stepflow/v1;stepflowv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stepflow.v1.vsock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/datastax/stepflow/proto/stepflow/v1;stepflowv1'
  _globals['_VSOCKTASKENVELOPE']._serialized_start=66
  _globals['_VSOCKTASKENVELOPE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
