// Copyright 2025 DataStax Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
// in compliance with the License. You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied. See the License for the specific language governing permissions and limitations under
// the License.

//! gRPC protocol definitions and services for Stepflow.
//!
//! This crate contains:
//! - Generated protobuf types and gRPC service definitions
//! - Service implementations for the orchestrator (RunsService, BlobService, etc.)
//! - Queue-based plugin for dispatching tasks to workers
//! - Task completion registry for correlating results

/// Proto types and gRPC service definitions re-exported from `stepflow-proto`.
///
/// Preserves the `crate::proto::stepflow::v1::*` path that existing code and
/// generated REST route handlers reference.
pub mod proto {
    pub use stepflow_proto::*;
}

// Re-export so generated REST routes can use `crate::stepflow::v1::*`
pub use proto::stepflow;

/// Build-time metadata generated by the `built` crate (git commit, dirty, etc.).
#[allow(dead_code)]
mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

pub mod blob_binary_routes;
pub mod component_health;
pub mod conversions;
pub mod error;
pub mod grpc_plugin_config;
pub mod grpc_server;
pub mod in_memory_transport;
pub mod pending_tasks;
pub mod pull_task_queue;
pub mod queue_plugin;
mod services;
pub mod task_transport;
pub mod transport_compliance;

/// Generated REST route handlers from `google.api.http` annotations.
#[allow(
    clippy::all,
    clippy::unused_trait_names,
    unfulfilled_lint_expectations,
    unused_imports
)]
pub mod rest {
    include!(concat!(env!("OUT_DIR"), "/rest_routes.rs"));
}

// Re-export commonly used types at the crate root.
pub use component_health::ComponentHealthTracker;
pub use grpc_plugin_config::{GrpcPluginConfig, GrpcPluginFactory};
pub use grpc_server::StepflowGrpcServer;
pub use in_memory_transport::InMemoryTaskTransport;
pub use pending_tasks::PendingTasks;
pub use proto::stepflow::v1::*;
pub use pull_task_queue::PullTaskQueue;
pub use queue_plugin::StepflowQueuePlugin;
pub use services::*;
pub use task_transport::TaskTransport;
