# Stepflow Configuration with Pingora Load Balancer
#
# This configuration routes through Pingora for proper instance affinity
# with bidirectional components.

plugins:
  # Built-in components for core Stepflow functionality
  builtin:
    type: builtin

  # Kubernetes components via Pingora load balancer
  k8s_components:
    type: stepflow
    transport: http
    url: "http://localhost:8080"  # Port-forwarded Pingora LB
    # In production: url: "http://pingora-lb.stepflow-demo.svc.cluster.local:8080"

routes:
  # Route all /python/* components through Pingora
  # Pingora handles instance routing via Stepflow-Instance-Id header
  "/python/{*component}":
    - plugin: k8s_components

  # Fallback to built-in components
  "/{*component}":
    - plugin: builtin

# In-memory state store (sufficient for single-workflow testing)
stateStore:
  type: inMemory
