# Stepflow Configuration for Kubernetes Batch Demo
#
# This configuration routes component execution to Kubernetes pods
# while keeping the Stepflow runtime simple (single instance, SQLite state).

plugins:
  # Built-in components for core Stepflow functionality
  builtin:
    type: builtin

  # Kubernetes component servers via port-forward
  # In production, this would be a LoadBalancer or Ingress URL
  k8s_components:
    type: stepflow
    transport: http
    url: "http://localhost:8080"
    # When deployed: url: "http://component-server.stepflow-demo.svc.cluster.local:8080"

routes:
  # Route all /python/* components to k8s component servers
  "/python/{*component}":
    - plugin: k8s_components

  # Fallback to built-in components for everything else
  "/{*component}":
    - plugin: builtin

# SQLite state store (sufficient for single runtime)
stateStore:
  type: sqlite
  databaseUrl: "sqlite:./k8s_batch_demo.db"
  autoMigrate: true
  maxConnections: 10
