# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

# coding: utf-8

"""
Stepflow API

API for Stepflow flows and runs

The version of the OpenAPI document: 0.9.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum
from typing import Self


class DiagnosticLevel(str, Enum):
    """
    Diagnostic level indicating severity and impact
    """

    """
    allowed enum values
    """
    FATAL = "fatal"
    ERROR = "error"
    WARNING = "warning"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DiagnosticLevel from a JSON string"""
        return cls(json.loads(json_str))
