# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

# coding: utf-8

"""
Stepflow API

API for Stepflow flows and runs

The version of the OpenAPI document: 0.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Self

from pydantic import (
    BaseModel,
    ConfigDict,
    ValidationError,
    field_validator,
    model_serializer,
)

from stepflow_py.api.models.path_part_one_of import PathPartOneOf
from stepflow_py.api.models.path_part_one_of1 import PathPartOneOf1

PATHPART_ONE_OF_SCHEMAS = ["PathPartOneOf", "PathPartOneOf1"]


class PathPart(BaseModel):
    """
    PathPart
    """

    # data type: PathPartOneOf
    oneof_schema_1_validator: PathPartOneOf | None = None
    # data type: PathPartOneOf1
    oneof_schema_2_validator: PathPartOneOf1 | None = None
    actual_instance: PathPartOneOf | PathPartOneOf1 | None = None
    one_of_schemas: set[str] = {"PathPartOneOf", "PathPartOneOf1"}

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    @model_serializer(mode="plain")
    def _serialize(self) -> Any:
        """Serialize by returning only the actual_instance, ignoring wrapper fields."""
        return self.actual_instance

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = PathPart.model_construct()
        error_messages = []
        match = 0
        # validate data type: PathPartOneOf
        if not isinstance(v, PathPartOneOf):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `PathPartOneOf`"
            )
        else:
            match += 1
        # validate data type: PathPartOneOf1
        if not isinstance(v, PathPartOneOf1):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `PathPartOneOf1`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in PathPart with oneOf schemas: PathPartOneOf, PathPartOneOf1. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in PathPart with oneOf schemas: PathPartOneOf, PathPartOneOf1. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: str | dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PathPartOneOf
        try:
            instance.actual_instance = PathPartOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PathPartOneOf1
        try:
            instance.actual_instance = PathPartOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into PathPart with oneOf schemas: PathPartOneOf, PathPartOneOf1. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into PathPart with oneOf schemas: PathPartOneOf, PathPartOneOf1. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict[str, Any] | PathPartOneOf | PathPartOneOf1 | None:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
