# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

# coding: utf-8

"""
Stepflow API

API for Stepflow flows and runs

The version of the OpenAPI document: 0.11.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Self

from pydantic import (
    BaseModel,
    ConfigDict,
    ValidationError,
    field_validator,
)

from stepflow_py.api.models.status_event_one_of import StatusEventOneOf
from stepflow_py.api.models.status_event_one_of1 import StatusEventOneOf1
from stepflow_py.api.models.status_event_one_of2 import StatusEventOneOf2
from stepflow_py.api.models.status_event_one_of3 import StatusEventOneOf3
from stepflow_py.api.models.status_event_one_of4 import StatusEventOneOf4
from stepflow_py.api.models.status_event_one_of5 import StatusEventOneOf5
from stepflow_py.api.models.status_event_one_of6 import StatusEventOneOf6
from stepflow_py.api.models.status_event_one_of7 import StatusEventOneOf7

STATUSEVENT_ONE_OF_SCHEMAS = [
    "StatusEventOneOf",
    "StatusEventOneOf1",
    "StatusEventOneOf2",
    "StatusEventOneOf3",
    "StatusEventOneOf4",
    "StatusEventOneOf5",
    "StatusEventOneOf6",
    "StatusEventOneOf7",
]


class StatusEvent(BaseModel):
    """
    A public-facing event from the execution journal stream.  These events map from internal `JournalEvent` variants to user-friendly names and shapes. \"Task\" terminology is replaced with \"step\" since that's the user-facing concept.  Sent as SSE events with: - `id` = journal sequence number - `event` = variant name in snake_case (e.g., `step_started`) - `data` = JSON-serialized event payload
    """

    # data type: StatusEventOneOf
    oneof_schema_1_validator: StatusEventOneOf | None = None
    # data type: StatusEventOneOf1
    oneof_schema_2_validator: StatusEventOneOf1 | None = None
    # data type: StatusEventOneOf2
    oneof_schema_3_validator: StatusEventOneOf2 | None = None
    # data type: StatusEventOneOf3
    oneof_schema_4_validator: StatusEventOneOf3 | None = None
    # data type: StatusEventOneOf4
    oneof_schema_5_validator: StatusEventOneOf4 | None = None
    # data type: StatusEventOneOf5
    oneof_schema_6_validator: StatusEventOneOf5 | None = None
    # data type: StatusEventOneOf6
    oneof_schema_7_validator: StatusEventOneOf6 | None = None
    # data type: StatusEventOneOf7
    oneof_schema_8_validator: StatusEventOneOf7 | None = None
    actual_instance: (
        StatusEventOneOf
        | StatusEventOneOf1
        | StatusEventOneOf2
        | StatusEventOneOf3
        | StatusEventOneOf4
        | StatusEventOneOf5
        | StatusEventOneOf6
        | StatusEventOneOf7
        | None
    ) = None
    one_of_schemas: set[str] = {
        "StatusEventOneOf",
        "StatusEventOneOf1",
        "StatusEventOneOf2",
        "StatusEventOneOf3",
        "StatusEventOneOf4",
        "StatusEventOneOf5",
        "StatusEventOneOf6",
        "StatusEventOneOf7",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = StatusEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: StatusEventOneOf
        if not isinstance(v, StatusEventOneOf):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventOneOf`"
            )
        else:
            match += 1
        # validate data type: StatusEventOneOf1
        if not isinstance(v, StatusEventOneOf1):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventOneOf1`"
            )
        else:
            match += 1
        # validate data type: StatusEventOneOf2
        if not isinstance(v, StatusEventOneOf2):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventOneOf2`"
            )
        else:
            match += 1
        # validate data type: StatusEventOneOf3
        if not isinstance(v, StatusEventOneOf3):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventOneOf3`"
            )
        else:
            match += 1
        # validate data type: StatusEventOneOf4
        if not isinstance(v, StatusEventOneOf4):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventOneOf4`"
            )
        else:
            match += 1
        # validate data type: StatusEventOneOf5
        if not isinstance(v, StatusEventOneOf5):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventOneOf5`"
            )
        else:
            match += 1
        # validate data type: StatusEventOneOf6
        if not isinstance(v, StatusEventOneOf6):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventOneOf6`"
            )
        else:
            match += 1
        # validate data type: StatusEventOneOf7
        if not isinstance(v, StatusEventOneOf7):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventOneOf7`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in StatusEvent with oneOf schemas: StatusEventOneOf, StatusEventOneOf1, StatusEventOneOf2, StatusEventOneOf3, StatusEventOneOf4, StatusEventOneOf5, StatusEventOneOf6, StatusEventOneOf7. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in StatusEvent with oneOf schemas: StatusEventOneOf, StatusEventOneOf1, StatusEventOneOf2, StatusEventOneOf3, StatusEventOneOf4, StatusEventOneOf5, StatusEventOneOf6, StatusEventOneOf7. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: str | dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into StatusEventOneOf
        try:
            instance.actual_instance = StatusEventOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventOneOf1
        try:
            instance.actual_instance = StatusEventOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventOneOf2
        try:
            instance.actual_instance = StatusEventOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventOneOf3
        try:
            instance.actual_instance = StatusEventOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventOneOf4
        try:
            instance.actual_instance = StatusEventOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventOneOf5
        try:
            instance.actual_instance = StatusEventOneOf5.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventOneOf6
        try:
            instance.actual_instance = StatusEventOneOf6.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventOneOf7
        try:
            instance.actual_instance = StatusEventOneOf7.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into StatusEvent with oneOf schemas: StatusEventOneOf, StatusEventOneOf1, StatusEventOneOf2, StatusEventOneOf3, StatusEventOneOf4, StatusEventOneOf5, StatusEventOneOf6, StatusEventOneOf7. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into StatusEvent with oneOf schemas: StatusEventOneOf, StatusEventOneOf1, StatusEventOneOf2, StatusEventOneOf3, StatusEventOneOf4, StatusEventOneOf5, StatusEventOneOf6, StatusEventOneOf7. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> (
        dict[str, Any]
        | StatusEventOneOf
        | StatusEventOneOf1
        | StatusEventOneOf2
        | StatusEventOneOf3
        | StatusEventOneOf4
        | StatusEventOneOf5
        | StatusEventOneOf6
        | StatusEventOneOf7
        | None
    ):
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
