# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

# coding: utf-8

"""
Stepflow API

API for Stepflow flows and runs

The version of the OpenAPI document: 0.11.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Self

from pydantic import (
    BaseModel,
    ConfigDict,
    ValidationError,
    field_validator,
)

from stepflow_py.api.models.status_event_item_completed import StatusEventItemCompleted
from stepflow_py.api.models.status_event_run_completed import StatusEventRunCompleted
from stepflow_py.api.models.status_event_run_created import StatusEventRunCreated
from stepflow_py.api.models.status_event_step_completed import StatusEventStepCompleted
from stepflow_py.api.models.status_event_step_ready import StatusEventStepReady
from stepflow_py.api.models.status_event_step_started import StatusEventStepStarted
from stepflow_py.api.models.status_event_steps_needed import StatusEventStepsNeeded
from stepflow_py.api.models.status_event_sub_run_created import StatusEventSubRunCreated

STATUSEVENT_ONE_OF_SCHEMAS = [
    "StatusEventItemCompleted",
    "StatusEventRunCompleted",
    "StatusEventRunCreated",
    "StatusEventStepCompleted",
    "StatusEventStepReady",
    "StatusEventStepStarted",
    "StatusEventStepsNeeded",
    "StatusEventSubRunCreated",
]


class StatusEvent(BaseModel):
    """
    A status event with metadata from the execution journal.  Wraps a [`StatusEventKind`] with the journal sequence number and timestamp, providing a flat JSON structure via `#[serde(flatten)]`.
    """

    # data type: StatusEventRunCreated
    oneof_schema_1_validator: StatusEventRunCreated | None = None
    # data type: StatusEventStepStarted
    oneof_schema_2_validator: StatusEventStepStarted | None = None
    # data type: StatusEventStepCompleted
    oneof_schema_3_validator: StatusEventStepCompleted | None = None
    # data type: StatusEventStepsNeeded
    oneof_schema_4_validator: StatusEventStepsNeeded | None = None
    # data type: StatusEventStepReady
    oneof_schema_5_validator: StatusEventStepReady | None = None
    # data type: StatusEventItemCompleted
    oneof_schema_6_validator: StatusEventItemCompleted | None = None
    # data type: StatusEventRunCompleted
    oneof_schema_7_validator: StatusEventRunCompleted | None = None
    # data type: StatusEventSubRunCreated
    oneof_schema_8_validator: StatusEventSubRunCreated | None = None
    actual_instance: (
        StatusEventItemCompleted
        | StatusEventRunCompleted
        | StatusEventRunCreated
        | StatusEventStepCompleted
        | StatusEventStepReady
        | StatusEventStepStarted
        | StatusEventStepsNeeded
        | StatusEventSubRunCreated
        | None
    ) = None
    one_of_schemas: set[str] = {
        "StatusEventItemCompleted",
        "StatusEventRunCompleted",
        "StatusEventRunCreated",
        "StatusEventStepCompleted",
        "StatusEventStepReady",
        "StatusEventStepStarted",
        "StatusEventStepsNeeded",
        "StatusEventSubRunCreated",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = StatusEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: StatusEventRunCreated
        if not isinstance(v, StatusEventRunCreated):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventRunCreated`"
            )
        else:
            match += 1
        # validate data type: StatusEventStepStarted
        if not isinstance(v, StatusEventStepStarted):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventStepStarted`"
            )
        else:
            match += 1
        # validate data type: StatusEventStepCompleted
        if not isinstance(v, StatusEventStepCompleted):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventStepCompleted`"
            )
        else:
            match += 1
        # validate data type: StatusEventStepsNeeded
        if not isinstance(v, StatusEventStepsNeeded):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventStepsNeeded`"
            )
        else:
            match += 1
        # validate data type: StatusEventStepReady
        if not isinstance(v, StatusEventStepReady):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventStepReady`"
            )
        else:
            match += 1
        # validate data type: StatusEventItemCompleted
        if not isinstance(v, StatusEventItemCompleted):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventItemCompleted`"
            )
        else:
            match += 1
        # validate data type: StatusEventRunCompleted
        if not isinstance(v, StatusEventRunCompleted):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventRunCompleted`"
            )
        else:
            match += 1
        # validate data type: StatusEventSubRunCreated
        if not isinstance(v, StatusEventSubRunCreated):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `StatusEventSubRunCreated`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in StatusEvent with oneOf schemas: StatusEventItemCompleted, StatusEventRunCompleted, StatusEventRunCreated, StatusEventStepCompleted, StatusEventStepReady, StatusEventStepStarted, StatusEventStepsNeeded, StatusEventSubRunCreated. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in StatusEvent with oneOf schemas: StatusEventItemCompleted, StatusEventRunCompleted, StatusEventRunCreated, StatusEventStepCompleted, StatusEventStepReady, StatusEventStepStarted, StatusEventStepsNeeded, StatusEventSubRunCreated. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: str | dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into StatusEventRunCreated
        try:
            instance.actual_instance = StatusEventRunCreated.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventStepStarted
        try:
            instance.actual_instance = StatusEventStepStarted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventStepCompleted
        try:
            instance.actual_instance = StatusEventStepCompleted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventStepsNeeded
        try:
            instance.actual_instance = StatusEventStepsNeeded.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventStepReady
        try:
            instance.actual_instance = StatusEventStepReady.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventItemCompleted
        try:
            instance.actual_instance = StatusEventItemCompleted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventRunCompleted
        try:
            instance.actual_instance = StatusEventRunCompleted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StatusEventSubRunCreated
        try:
            instance.actual_instance = StatusEventSubRunCreated.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into StatusEvent with oneOf schemas: StatusEventItemCompleted, StatusEventRunCompleted, StatusEventRunCreated, StatusEventStepCompleted, StatusEventStepReady, StatusEventStepStarted, StatusEventStepsNeeded, StatusEventSubRunCreated. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into StatusEvent with oneOf schemas: StatusEventItemCompleted, StatusEventRunCompleted, StatusEventRunCreated, StatusEventStepCompleted, StatusEventStepReady, StatusEventStepStarted, StatusEventStepsNeeded, StatusEventSubRunCreated. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> (
        dict[str, Any]
        | StatusEventItemCompleted
        | StatusEventRunCompleted
        | StatusEventRunCreated
        | StatusEventStepCompleted
        | StatusEventStepReady
        | StatusEventStepStarted
        | StatusEventStepsNeeded
        | StatusEventSubRunCreated
        | None
    ):
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
