# This file was auto-generated by scripts/generate_api_client.py
# Do not edit manually - changes will be overwritten on regeneration.
#
# Generated from: openapi.json

# coding: utf-8

"""
Stepflow API

API for Stepflow flows and runs

The version of the OpenAPI document: 0.10.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum
from typing import Self


class StepStatus(str, Enum):
    """
    Status of an individual step within a workflow  Cases: * `blocked`: Step is waiting for dependencies to complete * `runnable`: Step is ready to be executed * `running`: Step is currently executing * `completed`: Step has been executed successfully * `skipped`: Step was skipped due to conditions * `failed`: Step failed with an error
    """

    """
    allowed enum values
    """
    BLOCKED = "blocked"
    RUNNABLE = "runnable"
    RUNNING = "running"
    COMPLETED = "completed"
    SKIPPED = "skipped"
    FAILED = "failed"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StepStatus from a JSON string"""
        return cls(json.loads(json_str))
