schema: https://stepflow.org/schemas/v1/flow.json
name: Basic Math Operations
description: Demonstrates basic mathematical operations using UDFs
schemas:
  type: object
  properties:
    input:
      type: object
      properties:
        m:
          type: integer
          description: First number
        n:
          type: integer
          description: Second number
    output:
      type: object
      properties:
        m_plus_n:
          type: integer
          description: Sum of m and n
        m_times_n:
          type: integer
          description: Product of m and n
        m_plus_n_times_n:
          type: integer
          description: Sum of m and n, multiplied by n
steps:
- id: create_addition_udf
  component: /builtin/put_blob
  input:
    data:
      input_schema:
        type: object
        properties:
          a:
            type: integer
          b:
            type: integer
        required:
        - a
        - b
      code: input['a'] + input['b']
    blob_type: data
- id: create_multiplication_udf
  component: /builtin/put_blob
  input:
    data:
      input_schema:
        type: object
        properties:
          a:
            type: integer
          b:
            type: integer
        required:
        - a
        - b
      code: input['a'] * input['b']
    blob_type: data
- id: m_plus_n
  component: /python/udf
  input:
    blob_id:
      $step: create_addition_udf
      path: blob_id
    input:
      a:
        $input: m
      b:
        $input: n
- id: m_times_n
  component: /python/udf
  input:
    blob_id:
      $step: create_multiplication_udf
      path: blob_id
    input:
      a:
        $input: m
      b:
        $input: n
- id: m_plus_n_times_n
  component: /python/udf
  input:
    blob_id:
      $step: create_multiplication_udf
      path: blob_id
    input:
      a:
        $step: m_plus_n
      b:
        $input: n
output:
  m_plus_n:
    $step: m_plus_n
  m_times_n:
    $step: m_times_n
  m_plus_n_times_n:
    $step: m_plus_n_times_n
test:
  cases:
  - name: calculate_with_8_and_5
    description: Test calculation with m=8, n=5
    input:
      m: 8
      n: 5
    output:
      outcome: success
      result:
        m_plus_n: 13
        m_plus_n_times_n: 65
        m_times_n: 40
  - name: calculate_with_3_and_4
    description: Test calculation with m=3, n=4 (from docs example)
    input:
      m: 3
      n: 4
    output:
      outcome: success
      result:
        m_plus_n: 7
        m_plus_n_times_n: 28
        m_times_n: 12
